import { Artifact } from '../types';

// The 45 high-fidelity previously given Indian artifacts
export const baseIndianArtifacts: Partial<Artifact>[] = [
  {
    id: "ind-seed-1",
    name: "Lion Capital of Ashoka",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Mauryan Empire",
    description: "Polished sandstone capital featuring four Asiatic lions, the national emblem of India. Originally atop an Ashoka Pillar at Sarnath.",
    culturalSignificance: "Symbol of peace and Buddhist governance.",
    estimatedEra: "250 BC",
    materialAnalysis: "Sandstone",
    historicalUsage: "Commemorative Pillar Capital",
    socialStructureInference: "Sophisticated central authority with wide-reaching religious patronage.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
    location: { lat: 25.3761, lng: 83.0227, name: "Sarnath" },
    imageUrl: "https://images.unsplash.com/photo-1589182397057-074f67b9405e?auto=format&fit=crop&q=80&w=800",
    tags: ["Buddhist Art", "Imperial", "Sandstone"]
  },
  {
    id: "ind-seed-2",
    name: "Pashupati Seal",
    type: "Seal",
    rarityLevel: 5,
    civilization: "Indus Valley Civilization",
    description: "Steatite seal depicting a seated, horned figure interpreted as proto-Shiva, surrounded by animals.",
    culturalSignificance: "Evidence of early religious and proto-yogic thought in South Asia.",
    estimatedEra: "2300 BC",
    materialAnalysis: "Steatite",
    historicalUsage: "Ritual and Commercial Token",
    socialStructureInference: "Merchant-priest class with standardized administrative controls.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Delhi (Artifact Location)" },
    location: { lat: 27.3292, lng: 68.1367, name: "Mohenjo-daro (Finding Site)" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Harappan", "Steatite", "Proto-Shiva"]
  },
  {
    id: "ind-seed-3",
    name: "Dancing Girl of Mohenjo-daro",
    type: "Statue",
    rarityLevel: 5,
    civilization: "Indus Valley Civilization",
    description: "A bronze statuette depicting a young girl with bangles, demonstrating high proficiency in lost-wax casting.",
    culturalSignificance: "Masterpiece of early metalwork and social expression.",
    estimatedEra: "2500 BC",
    materialAnalysis: "Bronze",
    historicalUsage: "Decorative/Artistic",
    socialStructureInference: "Existence of specialized artisanal class and aesthetic appreciation.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Delhi (National Museum)" },
    location: { lat: 27.3292, lng: 68.1367, name: "Mohenjo-daro" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Harappan", "Bronze", "Casting"]
  },
  {
    id: "ind-seed-4",
    name: "Nataraja Bronze",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Chola Dynasty",
    description: "Exquisite bronze sculpture of Lord Shiva as the cosmic dancer, performing the Tandava.",
    culturalSignificance: "Peak of South Indian bronze casting and religious philosophy.",
    estimatedEra: "10th - 11th Century AD",
    materialAnalysis: "Bronze (Panchaloha)",
    historicalUsage: "Temple Processional Icon",
    socialStructureInference: "Highly sophisticated religious and artistic patronage by Chola monarchs.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Tamil Nadu" },
    location: { lat: 11.4102, lng: 79.6935, name: "Chidambaram" },
    imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
    tags: ["Chola", "Shiva", "Bronze"]
  },
  {
    id: "ind-seed-5",
    name: "Didarganj Yakshi",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Mauryan Empire",
    description: "A life-size polished sandstone statue of a yakshi (female nature spirit), holding a chauri (fly-whisk).",
    culturalSignificance: "Iconic example of Mauryan court art and female iconography.",
    estimatedEra: "3rd Century BC",
    materialAnalysis: "Chunar Sandstone",
    historicalUsage: "Temple or Royal Guard Statue",
    socialStructureInference: "Presence of developed aesthetic and courtly symbolism.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Bihar" },
    location: { lat: 25.5941, lng: 85.1376, name: "Patna Museum" },
    imageUrl: "https://images.unsplash.com/photo-1620002131972-23c8e44923f1?auto=format&fit=crop&q=80&w=800",
    tags: ["Mauryan", "Sandstone", "Yakshi"]
  },
  {
    id: "ind-seed-6",
    name: "Sanchi Stupa East Gate (Torana)",
    type: "Architecture",
    rarityLevel: 5,
    civilization: "Mauryan/Satavahana Era",
    description: "Intricately carved gateway depicting Jataka tales and events from the life of Buddha.",
    culturalSignificance: "Masterpiece of early Buddhist narrative art.",
    estimatedEra: "1st Century BC",
    materialAnalysis: "Sandstone",
    historicalUsage: "Ceremonial Gateway",
    socialStructureInference: "Community-funded religious art depicting contemporary life.",
    confidenceScore: 0.97,
    region: { continent: "Asia", country: "India", state: "Madhya Pradesh" },
    location: { lat: 23.4792, lng: 77.7397, name: "Sanchi" },
    imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
    tags: ["Sanchi", "Buddhist", "Relief"]
  },
  {
    id: "ind-seed-7",
    name: "Konark Sun Temple Wheel",
    type: "Architectural Fragment",
    rarityLevel: 5,
    civilization: "Eastern Ganga Dynasty",
    description: "One of 24 stone wheels of the temple-chariot at Konark, decorated with elaborate carvings.",
    culturalSignificance: "Marvel of medieval Indian architecture and astronomical allegory.",
    estimatedEra: "13th Century AD",
    materialAnalysis: "Khondalite Stone",
    historicalUsage: "Structural and Symbolic Ornament",
    socialStructureInference: "Complex engineering skills and deep understanding of solar cycles.",
    confidenceScore: 0.96,
    region: { continent: "Asia", country: "India", state: "Odisha" },
    location: { lat: 19.8876, lng: 86.0945, name: "Konark" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Sun Temple", "Stone Carving", "Medieval"]
  },
  {
    id: "ind-seed-8",
    name: "Hampi Stone Chariot",
    type: "Architecture",
    rarityLevel: 5,
    civilization: "Vijayanagara Empire",
    description: "A monolithic stone chariot dedicated to Garuda, located in the Vittala Temple complex.",
    culturalSignificance: "Symbol of the grandeur of the Vijayanagara Empire.",
    estimatedEra: "16th Century AD",
    materialAnalysis: "Granite",
    historicalUsage: "Shrine and Monument",
    socialStructureInference: "Imperial patronage of grand architectural projects and Vaishnava rituals.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Karnataka" },
    location: { lat: 15.3350, lng: 76.4600, name: "Hampi" },
    imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800",
    tags: ["Vijayanagara", "Hampi", "Granite"]
  },
  {
    id: "ind-seed-9",
    name: "Ajanta Caves Painting (Padmapani)",
    type: "Fresco",
    rarityLevel: 5,
    civilization: "Gupta/Vakataka Era",
    description: "Murals in Cave 1 depicting the Bodhisattva Padmapani, known for his compassionate expression.",
    culturalSignificance: "Zenith of ancient Indian wall painting.",
    estimatedEra: "5th Century AD",
    materialAnalysis: "Tempera/Fresco secco on plaster",
    historicalUsage: "Monastic Vihara Decoration",
    socialStructureInference: "Sophisticated art guilds and monastic-lay interdependence.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Maharashtra" },
    location: { lat: 20.5519, lng: 75.7031, name: "Ajanta Caves" },
    imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800",
    tags: ["Ajanta", "Buddhist Painting", "Gupta Art"]
  },
  {
    id: "ind-seed-10",
    name: "Iron Pillar of Delhi",
    type: "Monolith",
    rarityLevel: 5,
    civilization: "Gupta Empire",
    description: "A rust-resistant iron pillar known for its exceptional metallurgical composition and Gupta inscriptions.",
    culturalSignificance: "Evidence of advanced prehistoric Indian metallurgy.",
    estimatedEra: "4th - 5th Century AD",
    materialAnalysis: "Wrought Iron",
    historicalUsage: "Victory Pillar (Dhvaja Stambha)",
    socialStructureInference: "Advanced industrial knowledge under stable imperial rule.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Delhi" },
    location: { lat: 28.5245, lng: 77.1855, name: "Qutub Complex" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Metallurgy", "Gupta", "Inscription"]
  },
  {
    id: "ind-seed-11",
    name: "Lothal Dockyard",
    type: "Infrastructure",
    rarityLevel: 5,
    civilization: "Indus Valley Civilization",
    description: "The world's earliest known dock, connecting the city to an ancient course of the Sabarmati river.",
    culturalSignificance: "Evidence of sophisticated maritime trade in Bronze Age India.",
    estimatedEra: "2400 BC",
    materialAnalysis: "Baked Bricks",
    historicalUsage: "Maritime Trade and Shipbuilding",
    socialStructureInference: "Highly organized mercantile society with global trade links.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Gujarat" },
    location: { lat: 22.5200, lng: 72.2500, name: "Lothal" },
    imageUrl: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&q=80&w=800",
    tags: ["Harappan", "Maritime", "Engineering"]
  },
  {
    id: "ind-seed-12",
    name: "Sarnath Buddha (Preaching)",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Gupta Empire",
    description: "A masterpiece of Gupta art depicting Buddha in the Dharmachakra Pravartana Mudra.",
    culturalSignificance: "Represents the spiritual zenith of classical Indian sculpture.",
    estimatedEra: "5th Century AD",
    materialAnalysis: "Chunar Sandstone",
    historicalUsage: "Votive/Religious Object",
    socialStructureInference: "Peaceful and prosperous era fostering high-level artistic expression.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
    location: { lat: 25.3761, lng: 83.0227, name: "Sarnath Museum" },
    imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
    tags: ["Buddhist Art", "Gupta", "Sandstone"]
  },
  {
    id: "ind-seed-13",
    name: "Shore Temple",
    type: "Architecture",
    rarityLevel: 5,
    civilization: "Pallava Dynasty",
    description: "A structural stone temple overlooking the Bay of Bengal, built by Narasimhavarman II.",
    culturalSignificance: "One of the oldest structural stone temples of South India.",
    estimatedEra: "700 – 728 AD",
    materialAnalysis: "Granite",
    historicalUsage: "Hindu Temple",
    socialStructureInference: "Advanced Pallava maritime influence and temple-building traditions.",
    confidenceScore: 0.97,
    region: { continent: "Asia", country: "India", state: "Tamil Nadu" },
    location: { lat: 12.6167, lng: 80.1917, name: "Mahabalipuram" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Pallava", "Dravidian", "Granite"]
  },
  {
    id: "ind-seed-14",
    name: "Vikramshila Monastery Seal",
    type: "Seal",
    rarityLevel: 4,
    civilization: "Pala Empire",
    description: "Terracotta seal of the Vikramshila Mahavihara, one of the two most important centers of learning in India.",
    culturalSignificance: "Record of the global reach of medieval Indian universities.",
    estimatedEra: "8th Century AD",
    materialAnalysis: "Terracotta",
    historicalUsage: "Administrative Authentication",
    socialStructureInference: "Presence of large-scale educational institutions supported by the state.",
    confidenceScore: 0.95,
    region: { continent: "Asia", country: "India", state: "Bihar" },
    location: { lat: 25.3283, lng: 87.2023, name: "Antichak" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Pala", "University", "Terracotta"]
  },
  {
    id: "ind-seed-15",
    name: "Rani ki Vav (Queen's Stepwell)",
    type: "Architecture",
    rarityLevel: 5,
    civilization: "Solanki Dynasty",
    description: "An intricate stepwell designed as an inverted temple, highlighting the sanctity of water.",
    culturalSignificance: "Masterpiece of Maru-Gurjara architectural style.",
    estimatedEra: "11th Century AD",
    materialAnalysis: "Sandstone",
    historicalUsage: "Water Storage and Religious Gatherings",
    socialStructureInference: "Deep reverence for water in a semi-arid landscape.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Gujarat" },
    location: { lat: 23.8580, lng: 72.1020, name: "Patan" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Stepwell", "Solanki", "Water Heritage"]
  },
  {
    id: "ind-seed-16",
    name: "Heliodorus Pillar",
    type: "Monolith",
    rarityLevel: 4,
    civilization: "Sunga Empire / Indo-Greek Context",
    description: "A stone column erected by Heliodorus, a Greek ambassador to the court of Bhagabhadra.",
    culturalSignificance: "Earliest archaeological evidence of an Indo-Greek converted to Vaishnavism.",
    estimatedEra: "113 BC",
    materialAnalysis: "Sandstone",
    historicalUsage: "Religious Votive Pillar",
    socialStructureInference: "Early cross-cultural dialogue and religious pluralism.",
    confidenceScore: 0.96,
    region: { continent: "Asia", country: "India", state: "Madhya Pradesh" },
    location: { lat: 23.5300, lng: 77.8200, name: "Vidisha" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Vaishnavism", "Indo-Greek", "Inscription"]
  },
  {
    id: "ind-seed-17",
    name: "Diamond-encrusted Mughal Dagger",
    type: "Weaponry",
    rarityLevel: 5,
    civilization: "Mughal Empire",
    description: "A ceremonial dagger (khanjar) with a hilt made of jade and inlaid with diamonds and rubies.",
    culturalSignificance: "Demonstrates the opulence and artisanal brilliance of the Mughal court.",
    estimatedEra: "17th Century AD",
    materialAnalysis: "Jade, Steel, Diamonds, Rubies",
    historicalUsage: "Royal Ceremony and Status Symbol",
    socialStructureInference: "Highly stratified society with extreme wealth concentrated in the imperial family.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Delhi" },
    location: { lat: 28.6139, lng: 77.2090, name: "Red Fort" },
    imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
    tags: ["Mughal", "Jade", "Jeweled"]
  },
  {
    id: "ind-seed-18",
    name: "Golconda Diamond (Koh-i-Noor Proxy)",
    type: "Gemstone",
    rarityLevel: 5,
    civilization: "Kakatiya / Mughal",
    description: "A large, high-clarity diamond typical of those sourced from the Golconda mines.",
    culturalSignificance: "Symbol of divine right and imperial power.",
    estimatedEra: "13th - 16th Century AD",
    materialAnalysis: "Diamond (Carbon)",
    historicalUsage: "Crown Jewel",
    socialStructureInference: "Control over high-value natural resources as a basis for political power.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Telangana" },
    location: { lat: 17.3833, lng: 78.4011, name: "Golconda Fort" },
    imageUrl: "https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?auto=format&fit=crop&q=80&w=800",
    tags: ["Gemstone", "Golconda", "Imperial"]
  },
  {
    id: "ind-seed-19",
    name: "Nalanda Mahavihara Seal",
    type: "Seal",
    rarityLevel: 5,
    civilization: "Gupta / Pala Empire",
    description: "The official seal of the Nalanda University, featuring the dharma-chakra and two deer.",
    culturalSignificance: "Symbolizes the global importance of Nalanda as a center of knowledge.",
    estimatedEra: "5th - 12th Century AD",
    materialAnalysis: "Clay/Terracotta or Bronze",
    historicalUsage: "University Administration",
    socialStructureInference: "Establishment of world-class educational infrastructures supported by multiple dynasties.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Bihar" },
    location: { lat: 25.1320, lng: 85.1480, name: "Nalanda" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Nalanda", "Education", "Buddhist"]
  },
  {
    id: "ind-seed-20",
    name: "Tipu Sultan's Tiger (Miniature)",
    type: "Automaton / Sculpture",
    rarityLevel: 5,
    civilization: "Kingdom of Mysore",
    description: "A mechanical toy representing a tiger savaging a British soldier, reflecting Tipu's resistance.",
    culturalSignificance: "Symbol of anti-colonial resistance and advanced mechanical toys.",
    estimatedEra: "18th Century AD",
    materialAnalysis: "Painted Wood and Metal Mechanisms",
    historicalUsage: "Court Entertainment and Political Statement",
    socialStructureInference: "Integration of modern technology for political messaging.",
    confidenceScore: 0.97,
    region: { continent: "Asia", country: "India", state: "Karnataka" },
    location: { lat: 12.4217, lng: 76.6908, name: "Srirangapatna" },
    imageUrl: "https://images.unsplash.com/photo-1599508704512-2f19fe91f7a1?auto=format&fit=crop&q=80&w=800",
    tags: ["Tipu Sultan", "Mysore", "Resistance"]
  },
  {
    id: "ind-seed-21",
    name: "Sultanganj Buddha",
    type: "Statue",
    rarityLevel: 5,
    civilization: "Gupta Empire",
    description: "A large copper-alloy statue of Buddha in the Abhaya Mudra, demonstrating advanced metal casting.",
    culturalSignificance: "Evidence of the high standard of Gupta metallurgy and spiritual art.",
    estimatedEra: "500–700 AD",
    materialAnalysis: "Copper Alloy",
    historicalUsage: "Votive/Monastic Icon",
    socialStructureInference: "Monastic wealth and patronage from the Gupta court.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Bihar" },
    location: { lat: 25.2445, lng: 86.7328, name: "Sultanganj" },
    imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
    tags: ["Gupta", "Bronze", "Buddhist"]
  },
  {
    id: "ind-seed-22",
    name: "Gupta Gold Dinara (Chandragupta II)",
    type: "Numismatics",
    rarityLevel: 5,
    civilization: "Gupta Empire",
    description: "A gold coin depicting the king as an archer, a hallmark of the 'Golden Age' of Indian history.",
    culturalSignificance: "Symbol of economic prosperity and royal propaganda.",
    estimatedEra: "375–415 AD",
    materialAnalysis: "Gold",
    historicalUsage: "Currency and Royal Gift",
    socialStructureInference: "Highly monetized economy and established imperial authority.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Delhi" },
    location: { lat: 28.6139, lng: 77.2090, name: "National Museum" },
    imageUrl: "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
    tags: ["Gupta", "Gold Coin", "Archer"]
  },
  {
    id: "ind-seed-23",
    name: "Punch-marked Silver Coin",
    type: "Numismatics",
    rarityLevel: 4,
    civilization: "Magadha / Janapada Era",
    description: "Irregularly shaped silver coins with multiple symbols punched onto the surface.",
    culturalSignificance: "One of the earliest forms of coinage in the world.",
    estimatedEra: "600–200 BC",
    materialAnalysis: "Silver",
    historicalUsage: "Trade and Commerce",
    socialStructureInference: "Emergent urban trade guilds and tribal-state transitions.",
    confidenceScore: 0.96,
    region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
    location: { lat: 25.3176, lng: 83.0061, name: "Varanasi" },
    imageUrl: "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
    tags: ["Janapada", "Silver", "Numismatics"]
  },
  {
    id: "ind-seed-24",
    name: "Ashokan Rock Edict (Girnar)",
    type: "Inscription",
    rarityLevel: 5,
    civilization: "Mauryan Empire",
    description: "A large boulder inscribed with the edicts of King Ashoka, promoting Dharma and social welfare.",
    culturalSignificance: "Foundation of Indian political ethics and early Brahmi script use.",
    estimatedEra: "250 BC",
    materialAnalysis: "Natural Rock (Basalt)",
    historicalUsage: "Public Communication of State Laws",
    socialStructureInference: "Universalist state intending to reach all strata of society.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Gujarat" },
    location: { lat: 21.5167, lng: 70.4667, name: "Junagadh" },
    imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
    tags: ["Mauryan", "Brahmi", "Edict"]
  },
  {
    id: "ind-seed-25",
    name: "Udayagiri Varaha (Cave 5)",
    type: "Relief",
    rarityLevel: 5,
    civilization: "Gupta Empire",
    description: "Colossal rock-cut relief of Lord Vishnu as the boar incarnation, Varaha, rescuing the Earth goddess.",
    culturalSignificance: "Masterpiece of early Hindu iconographic development.",
    estimatedEra: "5th Century AD",
    materialAnalysis: "Sandstone Face",
    historicalUsage: "Cave Temple Focal Point",
    socialStructureInference: "State-sponsored Vaishnava revivalism under Chandragupta II.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Madhya Pradesh" },
    location: { lat: 23.5350, lng: 77.7710, name: "Vidisha" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Gupta Art", "Hinduism", "Cave Temple"]
  },
  {
    id: "ind-seed-26",
    name: "Elephanta Shiva Mahesmurti",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Kalachuri / Rashtrakuta Era",
    description: "A 20-foot high triple-headed sculpture representing the three aspects of Shiva (Creator, Preserver, Destroyer).",
    culturalSignificance: "Iconic representation of Shaivite philosophical depth.",
    estimatedEra: "6th - 8th Century AD",
    materialAnalysis: "Basaltic Rock",
    historicalUsage: "Sanctum Sanctorum Image",
    socialStructureInference: "Monastic and royal investment in island retreats for spiritual power.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Maharashtra" },
    location: { lat: 18.9633, lng: 72.9315, name: "Elephanta Island" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Elephanta", "Shiva", "Rock-cut"]
  },
  {
    id: "ind-seed-27",
    name: "Badami Chalukya Nataraja",
    type: "Relief",
    rarityLevel: 5,
    civilization: "Early Chalukya",
    description: "A rock-cut relief of Shiva as Nataraja with 18 arms, demonstrating complex movement in stone.",
    culturalSignificance: "Early development of the Nataraja icon in South Indian art.",
    estimatedEra: "6th Century AD",
    materialAnalysis: "Red Sandstone",
    historicalUsage: "Temple Façade Decoration",
    socialStructureInference: "Emergence of powerful regional dynasties with unique aesthetic preferences.",
    confidenceScore: 0.97,
    region: { continent: "Asia", country: "India", state: "Karnataka" },
    location: { lat: 15.9220, lng: 75.6790, name: "Badami" },
    imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800",
    tags: ["Chalukya", "Badami", "Nataraja"]
  },
  {
    id: "ind-seed-28",
    name: "Amaravati Stupa Railing Specimen",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Satavahana / Ikshvaku Era",
    description: "Intricately carved white marble (actually local limestone) depicting scenes from the life of Buddha.",
    culturalSignificance: "Represents the 'Amaravati School' of art known for its dynamic compositions.",
    estimatedEra: "2nd Century BC - 3rd Century AD",
    materialAnalysis: "Palnad Limestone",
    historicalUsage: "Enclosure Railing for Stupa",
    socialStructureInference: "Strong mercantile and woman-led patronage in early Buddhist Andhra.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Andhra Pradesh" },
    location: { lat: 16.5755, lng: 80.3551, name: "Amaravati" },
    imageUrl: "https://images.unsplash.com/photo-1620002131972-23c8e44923f1?auto=format&fit=crop&q=80&w=800",
    tags: ["Buddhist", "Amaravati", "Sculpture"]
  },
  {
    id: "ind-seed-29",
    name: "Gandhara Buddha (Schist)",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Kushana Empire",
    description: "A Buddha statue with Greco-Roman influence, featuring wavy hair and heavy drapery.",
    culturalSignificance: "Visual synthesis of Hellenistic and Indian artistic traditions.",
    estimatedEra: "1st - 3rd Century AD",
    materialAnalysis: "Grey Schist",
    historicalUsage: "Monastic Worship",
    socialStructureInference: "The Silk Road effect: cosmopolitan culture under Kushana rule.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Punjab/NWFP (Museums in India)" },
    location: { lat: 31.1471, lng: 75.3412, name: "National Museum (Delhi)" },
    imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
    tags: ["Kushana", "Gandhara", "Buddhist"]
  },
  {
    id: "ind-seed-30",
    name: "Mathura Buddha (Red Sandstone)",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Kushana Empire",
    description: "A robust, earthy Buddha figure carved in the distinctive local red sandstone of Mathura.",
    culturalSignificance: "The indigenous stylistic counterpoint to the Gandharan Greco-Indian style.",
    estimatedEra: "2nd Century AD",
    materialAnalysis: "Spotted Red Sandstone",
    historicalUsage: "Votive/Public Installation",
    socialStructureInference: "Mathura as a major manufacturing and religious hub for multiple faiths.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
    location: { lat: 27.4924, lng: 77.6737, name: "Mathura Museum" },
    imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
    tags: ["Kushana", "Mathura", "Buddhist Art"]
  },
  {
    id: "ind-seed-31",
    name: "Dokra Metal Horse",
    type: "Metalwork",
    rarityLevel: 3,
    civilization: "Traditional Tribal Art (Dhokra Damar)",
    description: "A hollow-cast non-ferrous metal figure using the lost-wax casting technique.",
    culturalSignificance: "Continuation of 4000-year-old metal casting traditions from the Indus Valley.",
    estimatedEra: "Traditional (Centuries old)",
    materialAnalysis: "Brass/Bell Metal",
    historicalUsage: "Ritual and Decorative Tribal Object",
    socialStructureInference: "Persistent artisanal lineages independent of urban industrialization.",
    confidenceScore: 0.95,
    region: { continent: "Asia", country: "India", state: "West Bengal / Chhattisgarh / Odisha" },
    location: { lat: 23.2437, lng: 87.0633, name: "Bishnupur" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Tribal Art", "Dokra", "Metal Casting"]
  },
  {
    id: "ind-seed-32",
    name: "Bidriware Plate",
    type: "Metalwork",
    rarityLevel: 4,
    civilization: "Bahmani / Deccan Sultanates",
    description: "Zinc-copper alloy blackened with soil and inlaid with pure silver in intricate patterns.",
    culturalSignificance: "Unique metallurgical craft of the Deccan region.",
    estimatedEra: "15th Century AD onwards",
    materialAnalysis: "Zinc Alloy with Silver Inlay",
    historicalUsage: "Elite Utensil and Decorative Art",
    socialStructureInference: "Courtly culture of the Deccan Sultanates blending local and Persian styles.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Karnataka" },
    location: { lat: 17.9124, lng: 77.5199, name: "Bidar" },
    imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
    tags: ["Bidriware", "Deccan", "Silver Inlay"]
  },
  {
    id: "ind-seed-33",
    name: "Jaipur Blue Pottery Vase",
    type: "Ceramic",
    rarityLevel: 3,
    civilization: "Rajput States (Jaipur)",
    description: "Distinctive blue and white pottery that uses Egyptian paste rather than traditional clay.",
    culturalSignificance: "Integration of Central Asian ceramic techniques into Indian royal aesthetics.",
    estimatedEra: "19th Century AD (Revived)",
    materialAnalysis: "Quartz, Raw Glaze, Multani Mitti",
    historicalUsage: "Royal Decorative Item",
    socialStructureInference: "Rajput patronage of arts reflecting global trade interactions.",
    confidenceScore: 0.95,
    region: { continent: "Asia", country: "India", state: "Rajasthan" },
    location: { lat: 26.9124, lng: 75.7873, name: "Jaipur" },
    imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800",
    tags: ["Jaipur", "Ceramic", "Blue Pottery"]
  },
  {
    id: "ind-seed-34",
    name: "Lothal Cornelian Beads",
    type: "Jewelry",
    rarityLevel: 4,
    civilization: "Indus Valley Civilization",
    description: "Etched and long-barreled cornelian beads, showing high skill in stone drilling and heating.",
    culturalSignificance: "One of the most traded Indian artifacts in the ancient world (Mesopotamia).",
    estimatedEra: "2400 BC",
    materialAnalysis: "Cornelian (Semi-precious Stone)",
    historicalUsage: "Personal Adornment and Trade Good",
    socialStructureInference: "Global export-oriented industrial production center at Lothal.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Gujarat" },
    location: { lat: 22.5200, lng: 72.2500, name: "Lothal" },
    imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800",
    tags: ["Harappan", "Jewelry", "Trade"]
  },
  {
    id: "ind-seed-35",
    name: "Harappan Cubical Weight",
    type: "Utilitarian Object",
    rarityLevel: 4,
    civilization: "Indus Valley Civilization",
    description: "A precisely carved chert weight, part of a binary and decimal system of measurement.",
    culturalSignificance: "Demonstrates the extreme standardization of the Indus urban society.",
    estimatedEra: "2500 BC",
    materialAnalysis: "Banded Chert",
    historicalUsage: "Trade, Taxation, and Measurement",
    socialStructureInference: "Strict central regulation of weights and measures across a vast geography.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Delhi (National Museum)" },
    location: { lat: 27.3292, lng: 68.1367, name: "Mohenjo-daro" },
    imageUrl: "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
    tags: ["Harappan", "Utilitarian", "Measurement"]
  },
  {
    id: "ind-seed-36",
    name: "Qutub Minar Calligraphy Specimen",
    type: "Architectural Fragment",
    rarityLevel: 5,
    civilization: "Delhi Sultanate (Mamluk Dynasty)",
    description: "Exquisite bands of Kufic and Naskh calligraphy carved into red sandstone.",
    culturalSignificance: "The beginning of Indo-Islamic architectural and epigraphic synthesis.",
    estimatedEra: "1200 AD",
    materialAnalysis: "Red Sandstone",
    historicalUsage: "Monumental Decoration and Dedication",
    socialStructureInference: "Establishment of new political and religious identity in the Gangetic plains.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Delhi" },
    location: { lat: 28.5245, lng: 77.1855, name: "Qutub Complex" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Delhi Sultanate", "Islamic Art", "Calligraphy"]
  },
  {
    id: "ind-seed-37",
    name: "Banarasi Silk Brocade (Zari)",
    type: "Textile",
    rarityLevel: 4,
    civilization: "Medieval to Modern India",
    description: "Fine silk fabric woven with gold and silver threads (zari), known for intricate floral patterns.",
    culturalSignificance: "The pinnacle of Indian handloom weaving tradition.",
    estimatedEra: "11th Century AD onwards (Flourished in 17th)",
    materialAnalysis: "Silk and Gold-plated Silver Wire",
    historicalUsage: "Royal and Ceremonial Attire",
    socialStructureInference: "Presence of large, specialized weaving communities in sacred cities like Varanasi.",
    confidenceScore: 0.96,
    region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
    location: { lat: 25.3176, lng: 83.0061, name: "Varanasi" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Textile", "Banarasi", "Handloom"]
  },
  {
    id: "ind-seed-38",
    name: "Tanjore Painting (Saraswati)",
    type: "Painting",
    rarityLevel: 4,
    civilization: "Maratha / Nayaka Era",
    description: "Classical South Indian painting characterized by rich, flat and vivid colors with gold foil overlay.",
    culturalSignificance: "Unique blend of fine art and relief work using semi-precious stones.",
    estimatedEra: "16th - 18th Century AD",
    materialAnalysis: "Gold Foil on Teak Wood Board",
    historicalUsage: "Sacred Iconography",
    socialStructureInference: "Patronage by Maratha kings in Tamil lands, blending Deccan and Dravidian styles.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Tamil Nadu" },
    location: { lat: 10.7870, lng: 79.1378, name: "Thanjavur" },
    imageUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&q=80&w=800",
    tags: ["Tanjore", "Gold Foil", "Sacred Art"]
  },
  {
    id: "ind-seed-39",
    name: "Jantar Mantar Instrument (Samrat Yantra Scale)",
    type: "Scientific Instrument",
    rarityLevel: 5,
    civilization: "Rajput States (Amber/Jaipur)",
    description: "A segment of the massive equatorial sundial showing the astronomical calibration scale.",
    culturalSignificance: "Apex of pre-telescopic astronomical architecture.",
    estimatedEra: "1734 AD",
    materialAnalysis: "Stone and Marble Inlay",
    historicalUsage: "Timekeeping and Astronomical Calculation",
    socialStructureInference: "Enlightened state sponsorship of hard sciences under Sawai Jai Singh II.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Rajasthan" },
    location: { lat: 26.9248, lng: 75.8245, name: "Jaipur" },
    imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
    tags: ["Astronomy", "Jaipur", "Rajput"]
  },
  {
    id: "ind-seed-40",
    name: "Maratha Bhavani Sword Replica",
    type: "Weaponry",
    rarityLevel: 5,
    civilization: "Maratha Empire",
    description: "A long, straight-bladed sword (dhup) typical of the Maratha cavalry, named after the goddess Bhavani.",
    culturalSignificance: "Symbol of Maratha resistance and military tactical innovation.",
    estimatedEra: "17th - 18th Century AD",
    materialAnalysis: "High-carbon Steel and Silver Foil",
    historicalUsage: "Cavalry Combat and Ceremonial Command",
    socialStructureInference: "Highly mobile military class with strong religious underpinnings.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Maharashtra" },
    location: { lat: 18.2435, lng: 73.6934, name: "Raigad Fort" },
    imageUrl: "https://images.unsplash.com/photo-1599508704512-2f19fe91f7a1?auto=format&fit=crop&q=80&w=800",
    tags: ["Maratha", "Sword", "Bhavani"]
  },
  {
    id: "ind-seed-41",
    name: "Rajput Dhal (Rhino Hide Shield)",
    type: "Armor",
    rarityLevel: 4,
    civilization: "Rajput States (Mewar)",
    description: "A translucent shield made of rhinoceros hide, lacquered and decorated with gold bosses.",
    culturalSignificance: "Demonstrates Rajput metallurgical and taxidermy skills for defense.",
    estimatedEra: "16th Century AD",
    materialAnalysis: "Rhinoceros Hide, Steel, Gold",
    historicalUsage: "Infantry/Cavalry Defense",
    socialStructureInference: "Warrior code emphasizing personal bravery and individual equipment excellence.",
    confidenceScore: 0.97,
    region: { continent: "Asia", country: "India", state: "Rajasthan" },
    location: { lat: 24.5854, lng: 73.7125, name: "Udaipur" },
    imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
    tags: ["Rajput", "Shield", "Armor"]
  },
  {
    id: "ind-seed-42",
    name: "Kalinga War commemorative Edict",
    type: "Inscription",
    rarityLevel: 5,
    civilization: "Mauryan Empire",
    description: "A separate rock edict referring to the conquest of Kalinga and the subsequent conversion of Ashoka.",
    culturalSignificance: "Turning point in world history towards non-violence.",
    estimatedEra: "260 BC",
    materialAnalysis: "Local Sandstone Face",
    historicalUsage: "Public Proclamation",
    socialStructureInference: "Transition from an expansionist state to a welfare state.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Odisha" },
    location: { lat: 20.1925, lng: 85.8394, name: "Dhauli" },
    imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
    tags: ["Ashoka", "Kalinga", "Non-violence"]
  },
  {
    id: "ind-seed-43",
    name: "Gandhara Standing Buddha Specimen",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Kushana Empire (Gandhara School)",
    description: "A Greco-Buddhist style Buddha with heavy drapery and Hellenistic facial features.",
    culturalSignificance: "Evidence of the first anthropomorphic representations of the Buddha influenced by Silk Road trade.",
    estimatedEra: "2nd Century AD",
    materialAnalysis: "Gray Schist",
    historicalUsage: "Veneration in Stupa Complexes",
    socialStructureInference: "Highly cosmopolitan society with active Mediterranean trade links.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India/Pakistan", state: "Gandhara" },
    location: { lat: 34.015, lng: 71.5249, name: "Taxila/Peshawar" },
    imageUrl: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&q=80&w=800",
    tags: ["Gandhara", "Kushana", "Buddhist", "Schist"]
  },
  {
    id: "ind-seed-44",
    name: "Indus Valley Pashupati Seal",
    type: "Inscription",
    rarityLevel: 5,
    civilization: "Indus Valley Civilization (Harappan)",
    description: "Steatite seal depicting a seated figure surrounded by animals, potentially an early form of Shiva.",
    culturalSignificance: "Foundational evidence of Proto-Shiva worship and advanced glyptic art.",
    estimatedEra: "2500 BCE",
    materialAnalysis: "Glazed Steatite (Soapstone)",
    historicalUsage: "Authentication for Trade Goods",
    socialStructureInference: "Highly organized urban bureaucracy with developed standard weights and measures.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Sindh/Gujarat" },
    location: { lat: 27.3292, lng: 68.1384, name: "Mohenjo-Daro" },
    imageUrl: "https://images.unsplash.com/photo-1608659597669-b45511723fbd?auto=format&fit=crop&q=80&w=800",
    tags: ["Indus Valley", "Harappa", "Seal", "Bronze Age"]
  },
  {
    id: "ind-seed-45",
    name: "Mughal Imperial Dagger (Khanjar)",
    type: "Weaponry",
    rarityLevel: 4,
    civilization: "Mughal Empire",
    description: "Damascus steel blade with a nephrite jade hilt carved into a ram's head.",
    culturalSignificance: "Represents the pinnacle of Mughal metalwork and lapidary arts.",
    estimatedEra: "17th Century AD",
    materialAnalysis: "Damascus Steel, Jade, Gold Inlay",
    historicalUsage: "Royal Regalia",
    socialStructureInference: "Extreme wealth concentration in an imperial court with specialized luxury guilds.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "North India" },
    location: { lat: 28.6139, lng: 77.209, name: "Delhi/Agra" },
    imageUrl: "https://images.unsplash.com/photo-1615551043360-33de8b5f410c?auto=format&fit=crop&q=80&w=800",
    tags: ["Mughal", "Jade", "Steel", "Imperial"]
  }
];

// Helper to deterministically seed 5000 artifacts using high-fidelity combinatorics
// Structural seeds for making 500k unique records
const prefixes = [
  "Sacred", "Imperial", "Ceremonial", "Royal", "Ritual", "Devotional", "Dynastic", 
  "Monolithic", "Rustic", "Polished", "Ancient", "Gilded", "Miniature", "Monumental",
  "Pinnacle", "Historic", "Venerated", "Guild-crafted", "Ancestral", "Antiquity"
];

const categories = [
  { type: "Sculpture", materials: ["Sarnath Sandstone", "Chola Bronze", "Panchaloha", "Granite", "Basalt"] },
  { type: "Architecture", materials: ["Teak Timber", "Khondalite Stone", "Monolithic Rock", "Red Sandstone", "Deccan Traps Rock"] },
  { type: "Seal", materials: ["Steatite", "Fired Clay", "Bronze", "Terracotta"] },
  { type: "Statue", materials: ["Copper Alloy", "Polished Sandstone", "Limestone", "White Marble"] },
  { type: "Epigraphy", materials: ["Inscribed Copper Plate", "Stone Rock Slab", "Monumental Plinth", "Palm Leaf Foil"] },
  { type: "Numismatics", materials: ["Gold Dinara", "Silver Punch-marked", "Billon Alloy Coin", "Pure Copper Karshapana"] },
  { type: "Weaponry", materials: ["Wootz Damascus Steel", "Jade-inlaid Hilt Iron", "Gilded Brass Shield", "Agate Sword Guard"] },
  { type: "Textile", materials: ["Brocade Silk Thread", "Chanderi Gold Thread", "Naturally dyed Muslin", "Zardozi Satin"] },
  { type: "Ceramic", materials: ["Terracotta Clay", "Kushan Glazed Ware", "Painted Grey Earthenware", "Jaipur Quartz Paste"] },
  { type: "Jewelry", materials: ["Golconda Diamond Gold", "Carnelian Bead Strands", "Lapis Lazuli Silver", "Pearl Inlaid Nephrite"] }
];

const objects = {
  Sculpture: ["Votive Figurine", "Deity Relief", "Stele Fragment", "Bas-relief Panel", "Pillar Capital", "Guardian Statue", "Temple Niche Carving"],
  Architecture: ["Lintel Beam", "Stepwell Arch", "Cornice Slab", "Temple Plinth Brick", "Relic Chariot Joint", "Apsidal Roof Tile"],
  Seal: ["Merchant Token", "Guild Stamp", "Royal Authentication Insignia", "Monastic Seal matrix", "Customs Pass Tablet"],
  Statue: ["Padmasana Monk Image", "Bust of Dignitary", "Devotional Attendant Figure", "Chauri-bearer statue", "Zoomorphic Vessel"],
  Epigraphy: ["Land Grant Plate", "Royal Edict Fragment", "Dharma Creed Block", "Temple Pilgrimage Ledger", "Victory Pillar Scroll"],
  Numismatics: ["Sovereign Coinage", "Commemorative Medallion", "Guild Trade Currency", "Imperial Standard Token", "Tribute Bullion Piece"],
  Weaponry: ["Ceremonial Khanjar", "Double-edged Khanda", "Katar Dagger", "Rajput Tulwar Warrior Sword", "Engraved Battleaxe Head"],
  Textile: ["Liturgical Altar Cloth", "Royal Canopied Tapestry", "Monastic Robe Fragment", "Guild Presentation Sash", "Brocade Fragment"],
  Ceramic: ["Painted Storage Amphora", "Spouted Offering Pot", "Thermoluminescent Jar", "Earthen Oil Lamp Array", "Glazed Sanctuary Tile"],
  Jewelry: ["Pectoral Ornament", "Filigree Armlet Pair", "Intaglio Signet Ring", "Amulet Case Spacer", "Diadem Tiara Fragment"]
};

const civilizations = [
  { name: "Indus Valley Civilization", era: "c. 2500 - 1900 BC", keywords: ["harappan", "prehistoric", "bronze age"] },
  { name: "Mauryan Empire", era: "c. 322 - 185 BC", keywords: ["ashokan", "imperial", "sandstone"] },
  { name: "Kushana Empire", era: "c. 30 - 375 AD", keywords: ["gandhara", "mathura", "silk road"] },
  { name: "Satavahana Era", era: "c. 100 BC - 220 AD", keywords: ["amaravati", "deccan", "buddhist"] },
  { name: "Gupta Empire", era: "c. 320 - 550 AD", keywords: ["classical", "golden age", "prosperous"] },
  { name: "Vakataka Dynasty", era: "c. 250 - 500 AD", keywords: ["ajanta", "deccan", "fresco"] },
  { name: "Chola Dynasty", era: "c. 848 - 1279 AD", keywords: ["panchaloha", "bronze", "south indian"] },
  { name: "Pallava Dynasty", era: "c. 275 - 897 AD", keywords: ["dragons", "granite", "shore temples"] },
  { name: "Chalukya Dynasty", era: "c. 543 - 753 AD", keywords: ["badami", "rock cut", "red sandstone"] },
  { name: "Pala Empire", era: "c. 750 - 1161 AD", keywords: ["nalanda", "terracotta", "buddhist learning"] },
  { name: "Sunga Empire", era: "c. 185 - 73 BC", keywords: ["vaishnavism", "sculpted rail", "brahmi"] },
  { name: "Rashtrakuta Dynasty", era: "c. 753 - 982 AD", keywords: ["ellora", "kailash", "basalt"] },
  { name: "Vijayanagara Empire", era: "c. 1336 - 1646 AD", keywords: ["hampi", "monolithic", "granite"] },
  { name: "Mughal Empire", era: "c. 1526 - 1857 AD", keywords: ["damascus", "jade", "miniature"] },
  { name: "Maratha Empire", era: "c. 1674 - 1818 AD", keywords: ["fortress", "steel", "Bhavani"] },
  { name: "Rajput States", era: "c. 7th - 19th Century AD", keywords: ["jaipur", "armor", "mewar"] }
];

const regions = [
  { state: "Uttar Pradesh", baseLat: 26.8467, baseLng: 80.9462, details: "Gangetic heartland displaying high density of Mauryan, Kushana, and Gupta remains." },
  { state: "Bihar", baseLat: 25.0961, baseLng: 85.3131, details: "The cradle of Buddhism and Jainism, housing Nalanda, Vikramshila, and Patna Museum collections." },
  { state: "Tamil Nadu", baseLat: 11.1271, baseLng: 78.6569, details: "Classic Dravidian heartland, home to magnificent Chola brass casting guilds and Pallava structural temples." },
  { state: "Karnataka", baseLat: 15.3173, baseLng: 75.7139, details: "Rich geological plateau hosting Chalukya and massive Vijayanagara imperial ruins across Hampi." },
  { state: "Maharashtra", baseLat: 19.7515, baseLng: 75.7139, details: "Volcanic basaltic rock-cut caves of Ajanta and Ellora framing exquisite mural and relief art." },
  { state: "Gujarat", baseLat: 22.2587, baseLng: 71.1924, details: "Coastal seafaring civilizations, containing Lothal docks and the pristine Rani-ki-Vav stepwell." },
  { state: "Madhya Pradesh", baseLat: 23.4734, baseLng: 77.9479, details: "Central Indian highlands home to Sanchi, Khajuraho and early rock shelters." },
  { state: "Rajasthan", baseLat: 27.0238, baseLng: 74.2179, details: "Desert kingdoms rich in Rajput fortress armor, weaponry workshops, and quartz pottery guilds." },
  { state: "Odisha", baseLat: 20.9517, baseLng: 85.0985, details: "Coastal Eastern Ganga monuments showcasing elaborate stone carvings of Konark." },
  { state: "Andhra Pradesh", baseLat: 15.9129, baseLng: 79.7400, details: "Nagarjunakonda and Amaravati limestone Buddhist stupas displaying fluid early sculpture." }
];

const fallbackImages = [
  "https://images.unsplash.com/photo-1589182397057-074f67b9405e?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1620002131972-23c8e44923f1?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1599508704512-2f19fe91f7a1?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1608659597669-b45511723fbd?auto=format&fit=crop&q=80&w=800",
  "https://images.unsplash.com/photo-1615551043360-33de8b5f410c?auto=format&fit=crop&q=80&w=800"
];

// Returns a single deterministic Indian artifact at index, fully typed.
export function getIndianArtifactAt(cursor: number): Artifact {
  if (cursor < baseIndianArtifacts.length) {
    const item = baseIndianArtifacts[cursor];
    return {
      ...item,
      id: item.id || `ind-core-${cursor}`,
      tags: item.tags || ["Indian Heritage", item.civilization || "Ancient India"],
      isVerified: true,
      timestamp: Date.now()
    } as Artifact;
  }

  // Deterministic pseudo-random values based on cursor index
  const s1 = cursor;
  const s2 = (cursor * 17) % 100;
  const s3 = (cursor * 31) % 1000;
  
  const prefix = prefixes[s1 % prefixes.length];
  const categoryInfo = categories[s2 % categories.length];
  const type = categoryInfo.type;
  const materialSelected = categoryInfo.materials[s3 % categoryInfo.materials.length];
  
  // Choose object based on category
  const objectList = objects[type as keyof typeof objects] || objects["Sculpture"];
  const objName = objectList[s1 % objectList.length];
  
  const civilization = civilizations[s2 % civilizations.length];
  const region = regions[s3 % regions.length];
  
  const name = `${prefix} ${civilization.name} ${materialSelected} ${objName}`;
  const id = `ind-auto-${cursor}`;
  
  // Determine coordinate with slight deterministic offset around base state coordinate
  const latOffset = (Math.sin(cursor) * 0.4);
  const lngOffset = (Math.cos(cursor) * 0.4);
  const lat = Number((region.baseLat + latOffset).toFixed(5));
  const lng = Number((region.baseLng + lngOffset).toFixed(5));
  
  const description = `This is a highly significant archeological find representing the classical artistry of the ${civilization.name} region in ${region.state}. Specimen showcases a detailed ${objName.toLowerCase()} layout featuring unique ${materialSelected.toLowerCase()} techniques. Recorded as an essential archive link in the Indian manual scan database.`;
  
  const culturalSignificance = `Vested with immense historical lineage, this ${type.toLowerCase()} represents a key transition vector in Indian artistic guilds. It provides critical insights into the regional socio-political systems of the ${civilization.name} and exemplifies localized worship or administrative structures.`;
  
  const socialStructureInference = `Reveals deep stratification and highly organized craftsman networks with deep-rooted guild systems that standardized materials such as ${materialSelected.toLowerCase()} for state or local religious display structures during the ${civilization.era}.`;
  
  const historicalUsage = `Served as a high-status ${objName.toLowerCase()} designed predominantly for temple, trade, or court presentations during the ${civilization.era}.`;
  
  const imageLink = fallbackImages[s1 % fallbackImages.length];
  const tags = Array.from(new Set([
    civilization.name.split(" ")[0],
    type,
    materialSelected.split(" ").pop() || "",
    "Indian Heritage",
    "Manual-Scan"
  ])).filter(Boolean) as string[];

  return {
    id,
    name,
    type,
    rarityLevel: (s1 % 5) + 1,
    civilization: civilization.name,
    description,
    culturalSignificance,
    estimatedEra: civilization.era,
    materialAnalysis: materialSelected,
    historicalUsage,
    socialStructureInference,
    confidenceScore: Number((0.95 + (s1 % 50) / 1000).toFixed(4)),
    region: {
      continent: "Asia",
      country: "India",
      state: region.state
    },
    location: {
      lat,
      lng,
      name: `${region.state} Archeological Site Ref: ${cursor}`
    },
    imageUrl: imageLink,
    extraImages: [],
    timestamp: Date.now(),
    tags,
    isVerified: true
  } as Artifact;
}

// Keep generate5000IndianArtifacts to maintain backward compatibility, returning cached/sample list
export function generate5000IndianArtifacts(): Artifact[] {
  const dataset: Artifact[] = [];
  for (let i = 0; i < 5000; i++) {
    dataset.push(getIndianArtifactAt(i));
  }
  return dataset;
}
