import { db } from './firebase';
import { collection, addDoc, getDocs, query, limit, serverTimestamp, setDoc, doc, getDoc } from 'firebase/firestore';
import { DUMMY_RESEARCHERS } from '../constants/dummyUsers';

const manualDataset = [
    {
        name: "Lion Capital of Ashoka",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Mauryan Empire",
        description: "Polished sandstone capital featuring four Asiatic lions, the national emblem of India. Originally atop an Ashoka Pillar at Sarnath.",
        culturalSignificance: "Symbol of peace and Buddhist governance.",
        estimatedEra: "250 BC",
        materialAnalysis: "Sandstone",
        historicalUsage: "Commemorative Pillar Capital",
        socialStructureInference: "Sophisticated central authority with wide-reaching religious patronage.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
        location: { lat: 25.3761, lng: 83.0227, name: "Sarnath" },
        imageUrl: "https://images.unsplash.com/photo-1589182397057-074f67b9405e?auto=format&fit=crop&q=80&w=800",
        tags: ["Buddhist Art", "Imperial", "Sandstone"]
    },
    {
        name: "Pashupati Seal",
        type: "Seal",
        rarityLevel: 5,
        civilization: "Indus Valley Civilization",
        description: "Steatite seal depicting a seated, horned figure interpreted as proto-Shiva, surrounded by animals.",
        culturalSignificance: "Evidence of early religious and proto-yogic thought in South Asia.",
        estimatedEra: "2300 BC",
        materialAnalysis: "Steatite",
        historicalUsage: "Ritual and Commercial Token",
        socialStructureInference: "Merchant-priest class with standardized administrative controls.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Delhi (Artifact Location)" },
        location: { lat: 27.3292, lng: 68.1367, name: "Mohenjo-daro (Finding Site)" },
        imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
        tags: ["Harappan", "Steatite", "Proto-Shiva"]
    },
    {
        name: "Dancing Girl of Mohenjo-daro",
        type: "Statue",
        rarityLevel: 5,
        civilization: "Indus Valley Civilization",
        description: "A bronze statuette depicting a young girl with bangles, demonstrating high proficiency in lost-wax casting.",
        culturalSignificance: "Masterpiece of early metalwork and social expression.",
        estimatedEra: "2500 BC",
        materialAnalysis: "Bronze",
        historicalUsage: "Decorative/Artistic",
        socialStructureInference: "Existence of specialized artisanal class and aesthetic appreciation.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Delhi (National Museum)" },
        location: { lat: 27.3292, lng: 68.1367, name: "Mohenjo-daro" },
        imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
        tags: ["Harappan", "Bronze", "Casting"]
    },
    {
        name: "Nataraja Bronze",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Chola Dynasty",
        description: "Exquisite bronze sculpture of Lord Shiva as the cosmic dancer, performing the Tandava.",
        culturalSignificance: "Peak of South Indian bronze casting and religious philosophy.",
        estimatedEra: "10th - 11th Century AD",
        materialAnalysis: "Bronze (Panchaloha)",
        historicalUsage: "Temple Processional Icon",
        socialStructureInference: "Highly sophisticated religious and artistic patronage by Chola monarchs.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Tamil Nadu" },
        location: { lat: 11.4102, lng: 79.6935, name: "Chidambaram" },
        imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
        tags: ["Chola", "Shiva", "Bronze"]
    },
    {
        name: "Didarganj Yakshi",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Mauryan Empire",
        description: "A life-size polished sandstone statue of a yakshi (female nature spirit), holding a chauri (fly-whisk).",
        culturalSignificance: "Iconic example of Mauryan court art and female iconography.",
        estimatedEra: "3rd Century BC",
        materialAnalysis: "Chunar Sandstone",
        historicalUsage: "Temple or Royal Guard Statue",
        socialStructureInference: "Presence of developed aesthetic and courtly symbolism.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Bihar" },
        location: { lat: 25.5941, lng: 85.1376, name: "Patna Museum" },
        imageUrl: "https://images.unsplash.com/photo-1620002131972-23c8e44923f1?auto=format&fit=crop&q=80&w=800",
        tags: ["Mauryan", "Sandstone", "Yakshi"]
    },
    {
        name: "Sanchi Stupa East Gate (Torana)",
        type: "Architecture",
        rarityLevel: 5,
        civilization: "Mauryan/Satavahana Era",
        description: "Intricately carved gateway depicting Jataka tales and events from the life of Buddha.",
        culturalSignificance: "Masterpiece of early Buddhist narrative art.",
        estimatedEra: "1st Century BC",
        materialAnalysis: "Sandstone",
        historicalUsage: "Ceremonial Gateway",
        socialStructureInference: "Community-funded religious art depicting contemporary life.",
        confidenceScore: 0.97,
        region: { continent: "Asia", country: "India", state: "Madhya Pradesh" },
        location: { lat: 23.4792, lng: 77.7397, name: "Sanchi" },
        imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
        tags: ["Sanchi", "Buddhist", "Relief"]
    },
    {
        name: "Konark Sun Temple Wheel",
        type: "Architectural Fragment",
        rarityLevel: 5,
        civilization: "Eastern Ganga Dynasty",
        description: "One of 24 stone wheels of the temple-chariot at Konark, decorated with elaborate carvings.",
        culturalSignificance: "Marvel of medieval Indian architecture and astronomical allegory.",
        estimatedEra: "13th Century AD",
        materialAnalysis: "Khondalite Stone",
        historicalUsage: "Structural and Symbolic Ornament",
        socialStructureInference: "Complex engineering skills and deep understanding of solar cycles.",
        confidenceScore: 0.96,
        region: { continent: "Asia", country: "India", state: "Odisha" },
        location: { lat: 19.8876, lng: 86.0945, name: "Konark" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Sun Temple", "Stone Carving", "Medieval"]
    },
    {
        name: "Hampi Stone Chariot",
        type: "Architecture",
        rarityLevel: 5,
        civilization: "Vijayanagara Empire",
        description: "A monolithic stone chariot dedicated to Garuda, located in the Vittala Temple complex.",
        culturalSignificance: "Symbol of the grandeur of the Vijayanagara Empire.",
        estimatedEra: "16th Century AD",
        materialAnalysis: "Granite",
        historicalUsage: "Shrine and Monument",
        socialStructureInference: "Imperial patronage of grand architectural projects and Vaishnava rituals.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Karnataka" },
        location: { lat: 15.3350, lng: 76.4600, name: "Hampi" },
        imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800",
        tags: ["Vijayanagara", "Hampi", "Granite"]
    },
    {
        name: "Ajanta Caves Painting (Padmapani)",
        type: "Fresco",
        rarityLevel: 5,
        civilization: "Gupta/Vakataka Era",
        description: "Murals in Cave 1 depicting the Bodhisattva Padmapani, known for his compassionate expression.",
        culturalSignificance: "Zenith of ancient Indian wall painting.",
        estimatedEra: "5th Century AD",
        materialAnalysis: "Tempera/Fresco secco on plaster",
        historicalUsage: "Monastic Vihara Decoration",
        socialStructureInference: "Sophisticated art guilds and monastic-lay interdependence.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Maharashtra" },
        location: { lat: 20.5519, lng: 75.7031, name: "Ajanta Caves" },
        imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800",
        tags: ["Ajanta", "Buddhist Painting", "Gupta Art"]
    },
    {
        name: "Iron Pillar of Delhi",
        type: "Monolith",
        rarityLevel: 5,
        civilization: "Gupta Empire",
        description: "A rust-resistant iron pillar known for its exceptional metallurgical composition and Gupta inscriptions.",
        culturalSignificance: "Evidence of advanced prehistoric Indian metallurgy.",
        estimatedEra: "4th - 5th Century AD",
        materialAnalysis: "Wrought Iron",
        historicalUsage: "Victory Pillar (Dhvaja Stambha)",
        socialStructureInference: "Advanced industrial knowledge under stable imperial rule.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Delhi" },
        location: { lat: 28.5245, lng: 77.1855, name: "Qutub Complex" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Metallurgy", "Gupta", "Inscription"]
    },
    {
        name: "Lothal Dockyard",
        type: "Infrastructure",
        rarityLevel: 5,
        civilization: "Indus Valley Civilization",
        description: "The world's earliest known dock, connecting the city to an ancient course of the Sabarmati river.",
        culturalSignificance: "Evidence of sophisticated maritime trade in Bronze Age India.",
        estimatedEra: "2400 BC",
        materialAnalysis: "Baked Bricks",
        historicalUsage: "Maritime Trade and Shipbuilding",
        socialStructureInference: "Highly organized mercantile society with global trade links.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Gujarat" },
        location: { lat: 22.5200, lng: 72.2500, name: "Lothal" },
        imageUrl: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&q=80&w=800",
        tags: ["Harappan", "Maritime", "Engineering"]
    },
    {
        name: "Sarnath Buddha (Preaching)",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Gupta Empire",
        description: "A masterpiece of Gupta art depicting Buddha in the Dharmachakra Pravartana Mudra.",
        culturalSignificance: "Represents the spiritual zenith of classical Indian sculpture.",
        estimatedEra: "5th Century AD",
        materialAnalysis: "Chunar Sandstone",
        historicalUsage: "Votive/Religious Object",
        socialStructureInference: "Peaceful and prosperous era fostering high-level artistic expression.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
        location: { lat: 25.3761, lng: 83.0227, name: "Sarnath Museum" },
        imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
        tags: ["Buddhist Art", "Gupta", "Sandstone"]
    },
    {
        name: "Shore Temple",
        type: "Architecture",
        rarityLevel: 5,
        civilization: "Pallava Dynasty",
        description: "A structural stone temple overlooking the Bay of Bengal, built by Narasimhavarman II.",
        culturalSignificance: "One of the oldest structural stone temples of South India.",
        estimatedEra: "700 – 728 AD",
        materialAnalysis: "Granite",
        historicalUsage: "Hindu Temple",
        socialStructureInference: "Advanced Pallava maritime influence and temple-building traditions.",
        confidenceScore: 0.97,
        region: { continent: "Asia", country: "India", state: "Tamil Nadu" },
        location: { lat: 12.6167, lng: 80.1917, name: "Mahabalipuram" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Pallava", "Dravidian", "Granite"]
    },
    {
        name: "Vikramshila Monastery Seal",
        type: "Seal",
        rarityLevel: 4,
        civilization: "Pala Empire",
        description: "Terracotta seal of the Vikramshila Mahavihara, one of the two most important centers of learning in India.",
        culturalSignificance: "Record of the global reach of medieval Indian universities.",
        estimatedEra: "8th Century AD",
        materialAnalysis: "Terracotta",
        historicalUsage: "Administrative Authentication",
        socialStructureInference: "Presence of large-scale educational institutions supported by the state.",
        confidenceScore: 0.95,
        region: { continent: "Asia", country: "India", state: "Bihar" },
        location: { lat: 25.3283, lng: 87.2023, name: "Antichak" },
        imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
        tags: ["Pala", "University", "Terracotta"]
    },
    {
        name: "Rani ki Vav (Queen's Stepwell)",
        type: "Architecture",
        rarityLevel: 5,
        civilization: "Solanki Dynasty",
        description: "An intricate stepwell designed as an inverted temple, highlighting the sanctity of water.",
        culturalSignificance: "Masterpiece of Maru-Gurjara architectural style.",
        estimatedEra: "11th Century AD",
        materialAnalysis: "Sandstone",
        historicalUsage: "Water Storage and Religious Gatherings",
        socialStructureInference: "Deep reverence for water in a semi-arid landscape.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Gujarat" },
        location: { lat: 23.8580, lng: 72.1020, name: "Patan" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Stepwell", "Solanki", "Water Heritage"]
    },
    {
        name: "Heliodorus Pillar",
        type: "Monolith",
        rarityLevel: 4,
        civilization: "Sunga Empire / Indo-Greek Context",
        description: "A stone column erected by Heliodorus, a Greek ambassador to the court of Bhagabhadra.",
        culturalSignificance: "Earliest archaeological evidence of an Indo-Greek converted to Vaishnavism.",
        estimatedEra: "113 BC",
        materialAnalysis: "Sandstone",
        historicalUsage: "Religious Votive Pillar",
        socialStructureInference: "Early cross-cultural dialogue and religious pluralism.",
        confidenceScore: 0.96,
        region: { continent: "Asia", country: "India", state: "Madhya Pradesh" },
        location: { lat: 23.5300, lng: 77.8200, name: "Vidisha" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Vaishnavism", "Indo-Greek", "Inscription"]
    },
    {
        name: "Diamond-encrusted Mughal Dagger",
        type: "Weaponry",
        rarityLevel: 5,
        civilization: "Mughal Empire",
        description: "A ceremonial dagger (khanjar) with a hilt made of jade and inlaid with diamonds and rubies.",
        culturalSignificance: "Demonstrates the opulence and artisanal brilliance of the Mughal court.",
        estimatedEra: "17th Century AD",
        materialAnalysis: "Jade, Steel, Diamonds, Rubies",
        historicalUsage: "Royal Ceremony and Status Symbol",
        socialStructureInference: "Highly stratified society with extreme wealth concentrated in the imperial family.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Delhi" },
        location: { lat: 28.6139, lng: 77.2090, name: "Red Fort" },
        imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
        tags: ["Mughal", "Jade", "Jeweled"]
    },
    {
        name: "Golconda Diamond (Koh-i-Noor Proxy)",
        type: "Gemstone",
        rarityLevel: 5,
        civilization: "Kakatiya / Mughal",
        description: "A large, high-clarity diamond typical of those sourced from the Golconda mines.",
        culturalSignificance: "Symbol of divine right and imperial power.",
        estimatedEra: "13th - 16th Century AD",
        materialAnalysis: "Diamond (Carbon)",
        historicalUsage: "Crown Jewel",
        socialStructureInference: "Control over high-value natural resources as a basis for political power.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Telangana" },
        location: { lat: 17.3833, lng: 78.4011, name: "Golconda Fort" },
        imageUrl: "https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?auto=format&fit=crop&q=80&w=800",
        tags: ["Gemstone", "Gloconda", "Imperial"]
    },
    {
        name: "Nalanda Mahavihara Seal",
        type: "Seal",
        rarityLevel: 5,
        civilization: "Gupta / Pala Empire",
        description: "The official seal of the Nalanda University, featuring the dharma-chakra and two deer.",
        culturalSignificance: "Symbolizes the global importance of Nalanda as a center of knowledge.",
        estimatedEra: "5th - 12th Century AD",
        materialAnalysis: "Clay/Terracotta or Bronze",
        historicalUsage: "University Administration",
        socialStructureInference: "Establishment of world-class educational infrastructures supported by multiple dynasties.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Bihar" },
        location: { lat: 25.1320, lng: 85.1480, name: "Nalanda" },
        imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
        tags: ["Nalanda", "Education", "Buddhist"]
    },
    {
        name: "Tipu Sultan's Tiger (Miniature)",
        type: "Automaton / Sculpture",
        rarityLevel: 5,
        civilization: "Kingdom of Mysore",
        description: "A mechanical toy representing a tiger savaging a British soldier, reflecting Tipu's resistance.",
        culturalSignificance: "Symbol of anti-colonial resistance and advanced mechanical toys.",
        estimatedEra: "18th Century AD",
        materialAnalysis: "Painted Wood and Metal Mechanisms",
        historicalUsage: "Court Entertainment and Political Statement",
        socialStructureInference: "Integration of modern technology for political messaging.",
        confidenceScore: 0.97,
        region: { continent: "Asia", country: "India", state: "Karnataka" },
        location: { lat: 12.4217, lng: 76.6908, name: "Srirangapatna" },
        imageUrl: "https://images.unsplash.com/photo-1599508704512-2f19fe91f7a1?auto=format&fit=crop&q=80&w=800",
        tags: ["Tipu Sultan", "Mysore", "Resistance"]
    },
    {
        name: "Sultanganj Buddha",
        type: "Statue",
        rarityLevel: 5,
        civilization: "Gupta Empire",
        description: "A large copper-alloy statue of Buddha in the Abhaya Mudra, demonstrating advanced metal casting.",
        culturalSignificance: "Evidence of the high standard of Gupta metallurgy and spiritual art.",
        estimatedEra: "500–700 AD",
        materialAnalysis: "Copper Alloy",
        historicalUsage: "Votive/Monastic Icon",
        socialStructureInference: "Monastic wealth and patronage from the Gupta court.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Bihar" },
        location: { lat: 25.2445, lng: 86.7328, name: "Sultanganj" },
        imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
        tags: ["Gupta", "Bronze", "Buddhist"]
    },
    {
        name: "Gupta Gold Dinara (Chandragupta II)",
        type: "Numismatics",
        rarityLevel: 5,
        civilization: "Gupta Empire",
        description: "A gold coin depicting the king as an archer, a hallmark of the 'Golden Age' of Indian history.",
        culturalSignificance: "Symbol of economic prosperity and royal propaganda.",
        estimatedEra: "375–415 AD",
        materialAnalysis: "Gold",
        historicalUsage: "Currency and Royal Gift",
        socialStructureInference: "Highly monetized economy and established imperial authority.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Delhi" },
        location: { lat: 28.6139, lng: 77.2090, name: "National Museum" },
        imageUrl: "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
        tags: ["Gupta", "Gold Coin", "Archer"]
    },
    {
        name: "Punch-marked Silver Coin",
        type: "Numismatics",
        rarityLevel: 4,
        civilization: "Magadha / Janapada Era",
        description: "Irregularly shaped silver coins with multiple symbols punched onto the surface.",
        culturalSignificance: "One of the earliest forms of coinage in the world.",
        estimatedEra: "600–200 BC",
        materialAnalysis: "Silver",
        historicalUsage: "Trade and Commerce",
        socialStructureInference: "Emergent urban trade guilds and tribal-state transitions.",
        confidenceScore: 0.96,
        region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
        location: { lat: 25.3176, lng: 83.0061, name: "Varanasi" },
        imageUrl: "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
        tags: ["Janapada", "Silver", "Numismatics"]
    },
    {
        name: "Ashokan Rock Edict (Girnar)",
        type: "Inscription",
        rarityLevel: 5,
        civilization: "Mauryan Empire",
        description: "A large boulder inscribed with the edicts of King Ashoka, promoting Dharma and social welfare.",
        culturalSignificance: "Foundation of Indian political ethics and early Brahmi script use.",
        estimatedEra: "250 BC",
        materialAnalysis: "Natural Rock (Basalt)",
        historicalUsage: "Public Communication of State Laws",
        socialStructureInference: "Universalist state intending to reach all strata of society.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Gujarat" },
        location: { lat: 21.5167, lng: 70.4667, name: "Junagadh" },
        imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
        tags: ["Mauryan", "Brahmi", "Edict"]
    },
    {
        name: "Udayagiri Varaha (Cave 5)",
        type: "Relief",
        rarityLevel: 5,
        civilization: "Gupta Empire",
        description: "Colossal rock-cut relief of Lord Vishnu as the boar incarnation, Varaha, rescuing the Earth goddess.",
        culturalSignificance: "Masterpiece of early Hindu iconographic development.",
        estimatedEra: "5th Century AD",
        materialAnalysis: "Sandstone Face",
        historicalUsage: "Cave Temple Focal Point",
        socialStructureInference: "State-sponsored Vaishnava revivalism under Chandragupta II.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Madhya Pradesh" },
        location: { lat: 23.5350, lng: 77.7710, name: "Vidisha" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Gupta Art", "Hinduism", "Cave Temple"]
    },
    {
        name: "Elephanta Shiva Mahesmurti",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Kalachuri / Rashtrakuta Era",
        description: "A 20-foot high triple-headed sculpture representing the three aspects of Shiva (Creator, Preserver, Destroyer).",
        culturalSignificance: "Iconic representation of Shaivite philosophical depth.",
        estimatedEra: "6th - 8th Century AD",
        materialAnalysis: "Basaltic Rock",
        historicalUsage: "Sanctum Sanctorum Image",
        socialStructureInference: "Monastic and royal investment in island retreats for spiritual power.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Maharashtra" },
        location: { lat: 18.9633, lng: 72.9315, name: "Elephanta Island" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Elephanta", "Shiva", "Rock-cut"]
    },
    {
        name: "Badami Chalukya Nataraja",
        type: "Relief",
        rarityLevel: 5,
        civilization: "Early Chalukya",
        description: "A rock-cut relief of Shiva as Nataraja with 18 arms, demonstrating complex movement in stone.",
        culturalSignificance: "Early development of the Nataraja icon in South Indian art.",
        estimatedEra: "6th Century AD",
        materialAnalysis: "Red Sandstone",
        historicalUsage: "Temple Façade Decoration",
        socialStructureInference: "Emergence of powerful regional dynasties with unique aesthetic preferences.",
        confidenceScore: 0.97,
        region: { continent: "Asia", country: "India", state: "Karnataka" },
        location: { lat: 15.9220, lng: 75.6790, name: "Badami" },
        imageUrl: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800",
        tags: ["Chalukya", "Badami", "Nataraja"]
    },
    {
        name: "Amaravati Stupa Railing Specimen",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Satavahana / Ikshvaku Era",
        description: "Intricately carved white marble (actually local limestone) depicting scenes from the life of Buddha.",
        culturalSignificance: "Represents the 'Amaravati School' of art known for its dynamic compositions.",
        estimatedEra: "2nd Century BC - 3rd Century AD",
        materialAnalysis: "Palnad Limestone",
        historicalUsage: "Enclosure Railing for Stupa",
        socialStructureInference: "Strong mercantile and woman-led patronage in early Buddhist Andhra.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Andhra Pradesh" },
        location: { lat: 16.5755, lng: 80.3551, name: "Amaravati" },
        imageUrl: "https://images.unsplash.com/photo-1620002131972-23c8e44923f1?auto=format&fit=crop&q=80&w=800",
        tags: ["Buddhist", "Amaravati", "Sculpture"]
    },
    {
        name: "Gandhara Buddha (Schist)",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Kushana Empire",
        description: "A Buddha statue with Greco-Roman influence, featuring wavy hair and heavy drapery.",
        culturalSignificance: "Visual synthesis of Hellenistic and Indian artistic traditions.",
        estimatedEra: "1st - 3rd Century AD",
        materialAnalysis: "Grey Schist",
        historicalUsage: "Monastic Worship",
        socialStructureInference: "The Silk Road effect: cosmopolitan culture under Kushana rule.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Punjab/NWFP (Museums in India)" },
        location: { lat: 31.1471, lng: 75.3412, name: "National Museum (Delhi)" },
        imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
        tags: ["Kushana", "Gandhara", "Buddhist"]
    },
    {
        name: "Mathura Buddha (Red Sandstone)",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Kushana Empire",
        description: "A robust, earthy Buddha figure carved in the distinctive local red sandstone of Mathura.",
        culturalSignificance: "The indigenous stylistic counterpoint to the Gandharan Greco-Indian style.",
        estimatedEra: "2nd Century AD",
        materialAnalysis: "Spotted Red Sandstone",
        historicalUsage: "Votive/Public Installation",
        socialStructureInference: "Mathura as a major manufacturing and religious hub for multiple faiths.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
        location: { lat: 27.4924, lng: 77.6737, name: "Mathura Museum" },
        imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
        tags: ["Kushana", "Mathura", "Buddhist Art"]
    },
    {
        name: "Dokra Metal Horse",
        type: "Metalwork",
        rarityLevel: 3,
        civilization: "Traditional Tribal Art (Dhokra Damar)",
        description: "A hollow-cast non-ferrous metal figure using the lost-wax casting technique.",
        culturalSignificance: "Continuation of 4000-year-old metal casting traditions from the Indus Valley.",
        estimatedEra: "Traditional (Centuries old)",
        materialAnalysis: "Brass/Bell Metal",
        historicalUsage: "Ritual and Decorative Tribal Object",
        socialStructureInference: "Persistent artisanal lineages independent of urban industrialization.",
        confidenceScore: 0.95,
        region: { continent: "Asia", country: "India", state: "West Bengal / Chhattisgarh / Odisha" },
        location: { lat: 23.2437, lng: 87.0633, name: "Bishnupur" },
        imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
        tags: ["Tribal Art", "Dokra", "Metal Casting"]
    },
    {
        name: "Bidriware Plate",
        type: "Metalwork",
        rarityLevel: 4,
        civilization: "Bahmani / Deccan Sultanates",
        description: "Zinc-copper alloy blackened with soil and inlaid with pure silver in intricate patterns.",
        culturalSignificance: "Unique metallurgical craft of the Deccan region.",
        estimatedEra: "15th Century AD onwards",
        materialAnalysis: "Zinc Alloy with Silver Inlay",
        historicalUsage: "Elite Utensil and Decorative Art",
        socialStructureInference: "Courtly culture of the Deccan Sultanates blending local and Persian styles.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Karnataka" },
        location: { lat: 17.9124, lng: 77.5199, name: "Bidar" },
        imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
        tags: ["Bidriware", "Deccan", "Silver Inlay"]
    },
    {
        name: "Jaipur Blue Pottery Vase",
        type: "Ceramic",
        rarityLevel: 3,
        civilization: "Rajput States (Jaipur)",
        description: "Distinctive blue and white pottery that uses Egyptian paste rather than traditional clay.",
        culturalSignificance: "Integration of Central Asian ceramic techniques into Indian royal aesthetics.",
        estimatedEra: "19th Century AD (Revived)",
        materialAnalysis: "Quartz, Raw Glaze, Multani Mitti",
        historicalUsage: "Royal Decorative Item",
        socialStructureInference: "Rajput patronage of arts reflecting global trade interactions.",
        confidenceScore: 0.95,
        region: { continent: "Asia", country: "India", state: "Rajasthan" },
        location: { lat: 26.9124, lng: 75.7873, name: "Jaipur" },
        imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800",
        tags: ["Jaipur", "Ceramic", "Blue Pottery"]
    },
    {
        name: "Lothal Cornelian Beads",
        type: "Jewelry",
        rarityLevel: 4,
        civilization: "Indus Valley Civilization",
        description: "Etched and long-barreled cornelian beads, showing high skill in stone drilling and heating.",
        culturalSignificance: "One of the most traded Indian artifacts in the ancient world (Mesopotamia).",
        estimatedEra: "2400 BC",
        materialAnalysis: "Cornelian (Semi-precious Stone)",
        historicalUsage: "Personal Adornment and Trade Good",
        socialStructureInference: "Global export-oriented industrial production center at Lothal.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Gujarat" },
        location: { lat: 22.5200, lng: 72.2500, name: "Lothal" },
        imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800",
        tags: ["Harappan", "Jewelry", "Trade"]
    },
    {
        name: "Harappan Cubical Weight",
        type: "Utilitarian Object",
        rarityLevel: 4,
        civilization: "Indus Valley Civilization",
        description: "A precisely carved chert weight, part of a binary and decimal system of measurement.",
        culturalSignificance: "Demonstrates the extreme standardization of the Indus urban society.",
        estimatedEra: "2500 BC",
        materialAnalysis: "Banded Chert",
        historicalUsage: "Trade, Taxation, and Measurement",
        socialStructureInference: "Strict central regulation of weights and measures across a vast geography.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Delhi (National Museum)" },
        location: { lat: 27.3292, lng: 68.1367, name: "Mohenjo-daro" },
        imageUrl: "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
        tags: ["Harappan", "Utilitarian", "Measurement"]
    },
    {
        name: "Qutub Minar Calligraphy Specimen",
        type: "Architectural Fragment",
        rarityLevel: 5,
        civilization: "Delhi Sultanate (Mamluk Dynasty)",
        description: "Exquisite bands of Kufic and Naskh calligraphy carved into red sandstone.",
        culturalSignificance: "The beginning of Indo-Islamic architectural and epigraphic synthesis.",
        estimatedEra: "1200 AD",
        materialAnalysis: "Red Sandstone",
        historicalUsage: "Monumental Decoration and Dedication",
        socialStructureInference: "Establishment of new political and religious identity in the Gangetic plains.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Delhi" },
        location: { lat: 28.5245, lng: 77.1855, name: "Qutub Complex" },
        imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
        tags: ["Delhi Sultanate", "Islamic Art", "Calligraphy"]
    },
    {
        name: "Banarasi Silk Brocade (Zari)",
        type: "Textile",
        rarityLevel: 4,
        civilization: "Medieval to Modern India",
        description: "Fine silk fabric woven with gold and silver threads (zari), known for intricate floral patterns.",
        culturalSignificance: "The pinnacle of Indian handloom weaving tradition.",
        estimatedEra: "11th Century AD onwards (Flourished in 17th)",
        materialAnalysis: "Silk and Gold-plated Silver Wire",
        historicalUsage: "Royal and Ceremonial Attire",
        socialStructureInference: "Presence of large, specialized weaving communities in sacred cities like Varanasi.",
        confidenceScore: 0.96,
        region: { continent: "Asia", country: "India", state: "Uttar Pradesh" },
        location: { lat: 25.3176, lng: 83.0061, name: "Varanasi" },
        imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
        tags: ["Textile", "Banarasi", "Handloom"]
    },
    {
        name: "Tanjore Painting (Saraswati)",
        type: "Painting",
        rarityLevel: 4,
        civilization: "Maratha / Nayaka Era",
        description: "Classical South Indian painting characterized by rich, flat and vivid colors with gold foil overlay.",
        culturalSignificance: "Unique blend of fine art and relief work using semi-precious stones.",
        estimatedEra: "16th - 18th Century AD",
        materialAnalysis: "Gold Foil on Teak Wood Board",
        historicalUsage: "Sacred Iconography",
        socialStructureInference: "Patronage by Maratha kings in Tamil lands, blending Deccan and Dravidian styles.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "Tamil Nadu" },
        location: { lat: 10.7870, lng: 79.1378, name: "Thanjavur" },
        imageUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&q=80&w=800",
        tags: ["Tanjore", "Gold Foil", "Sacred Art"]
    },
    {
        name: "Jantar Mantar Instrument (Samrat Yantra Scale)",
        type: "Scientific Instrument",
        rarityLevel: 5,
        civilization: "Rajput States (Amber/Jaipur)",
        description: "A segment of the massive equatorial sundial showing the astronomical calibration scale.",
        culturalSignificance: "A pex of pre-telescopic astronomical architecture.",
        estimatedEra: "1734 AD",
        materialAnalysis: "Stone and Marble Inlay",
        historicalUsage: "Timekeeping and Astronomical Calculation",
        socialStructureInference: "Enlightened state sponsorship of hard sciences under Sawai Jai Singh II.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Rajasthan" },
        location: { lat: 26.9248, lng: 75.8245, name: "Jaipur" },
        imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
        tags: ["Astronomy", "Jaipur", "Rajput"]
    },
    {
        name: "Maratha Bhavani Sword Replica",
        type: "Weaponry",
        rarityLevel: 5,
        civilization: "Maratha Empire",
        description: "A long, straight-bladed sword (dhup) typical of the Maratha cavalry, named after the goddess Bhavani.",
        culturalSignificance: "Symbol of Maratha resistance and military tactical innovation.",
        estimatedEra: "17th - 18th Century AD",
        materialAnalysis: "High-carbon Steel and Silver Foil",
        historicalUsage: "Cavalry Combat and Ceremonial Command",
        socialStructureInference: "Highly mobile military class with strong religious underpinnings.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India", state: "Maharashtra" },
        location: { lat: 18.2435, lng: 73.6934, name: "Raigad Fort" },
        imageUrl: "https://images.unsplash.com/photo-1599508704512-2f19fe91f7a1?auto=format&fit=crop&q=80&w=800",
        tags: ["Maratha", "Sword", "Bhavani"]
    },
    {
        name: "Rajput Dhal (Rhino Hide Shield)",
        type: "Armor",
        rarityLevel: 4,
        civilization: "Rajput States (Mewar)",
        description: "A translucent shield made of rhinoceros hide, lacquered and decorated with gold bosses.",
        culturalSignificance: "Demonstrates Rajput metallurgical and taxidermy skills for defense.",
        estimatedEra: "16th Century AD",
        materialAnalysis: "Rhinoceros Hide, Steel, Gold",
        historicalUsage: "Infantry/Cavalry Defense",
        socialStructureInference: "Warrior code emphasizing personal bravery and individual equipment excellence.",
        confidenceScore: 0.97,
        region: { continent: "Asia", country: "India", state: "Rajasthan" },
        location: { lat: 24.5854, lng: 73.7125, name: "Udaipur" },
        imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
        tags: ["Rajput", "Shield", "Armor"]
    },
    {
        name: "Kalinga War commemorative Edict",
        type: "Inscription",
        rarityLevel: 5,
        civilization: "Mauryan Empire",
        description: "A separate rock edict referring to the conquest of Kalinga and the subsequent conversion of Ashoka.",
        culturalSignificance: "Turning point in world history towards non-violence.",
        estimatedEra: "260 BC",
        materialAnalysis: "Local Sandstone Face",
        historicalUsage: "Public Proclamation",
        socialStructureInference: "Transition from an expansionist state to a welfare state.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Odisha" },
        location: { lat: 20.1925, lng: 85.8394, name: "Dhauli" },
        imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
        tags: ["Ashoka", "Kalinga", "Non-violence"]
    },
    {
        name: "Gandhara Standing Buddha Specimen",
        type: "Sculpture",
        rarityLevel: 5,
        civilization: "Kushana Empire (Gandhara School)",
        description: "A Greco-Buddhist style Buddha with heavy drapery and Hellenistic facial features.",
        culturalSignificance: "Evidence of the first anthropomorphic representations of the Buddha influenced by Silk Road trade.",
        historicalContext: "Found in the Peshawar valley, representing the syncretism of Greek and Indian art.",
        estimatedEra: "2nd Century AD",
        materialAnalysis: "Gray Schist",
        historicalUsage: "Veneration in Stupa Complexes",
        socialStructureInference: "Highly cosmopolitan society with active Mediterranean trade links.",
        confidenceScore: 0.99,
        region: { continent: "Asia", country: "India/Pakistan", state: "Gandhara" },
        location: { lat: 34.015, lng: 71.5249, name: "Taxila/Peshawar" },
        imageUrl: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&q=80&w=800",
        tags: ["Gandhara", "Kushana", "Buddhist", "Schist"]
    },
    {
        name: "Indus Valley Pashupati Seal",
        type: "Inscription",
        rarityLevel: 5,
        civilization: "Indus Valley Civilization (Harappan)",
        description: "Steatite seal depicting a seated figure surrounded by animals, potentially an early form of Shiva.",
        culturalSignificance: "Foundational evidence of Proto-Shiva worship and advanced glyptic art.",
        historicalContext: "Recovered from the lower town of Mohenjo-Daro.",
        estimatedEra: "2500 BCE",
        materialAnalysis: "Glazed Steatite (Soapstone)",
        historicalUsage: "Authentication for Trade Goods",
        socialStructureInference: "Highly organized urban bureaucracy with developed standard weights and measures.",
        confidenceScore: 1.0,
        region: { continent: "Asia", country: "India", state: "Sindh/Gujarat" },
        location: { lat: 27.3292, lng: 68.1384, name: "Mohenjo-Daro" },
        imageUrl: "https://images.unsplash.com/photo-1608659597669-b45511723fbd?auto=format&fit=crop&q=80&w=800",
        tags: ["Indus Valley", "Harappa", "Seal", "Bronze Age"]
    },
    {
        name: "Mughal Imperial Dagger (Khanjar)",
        type: "Weaponry",
        rarityLevel: 4,
        civilization: "Mughal Empire",
        description: "Damascus steel blade with a nephrite jade hilt carved into a ram's head.",
        culturalSignificance: "Represents the pinnacle of Mughal metalwork and lapidary arts.",
        historicalContext: "Likely belonging to the reign of Shah Jahan, used as a ceremonial status symbol.",
        estimatedEra: "17th Century AD",
        materialAnalysis: "Damascus Steel, Jade, Gold Inlay",
        historicalUsage: "Royal Regalia",
        socialStructureInference: "Extreme wealth concentration in an imperial court with specialized luxury guilds.",
        confidenceScore: 0.98,
        region: { continent: "Asia", country: "India", state: "North India" },
        location: { lat: 28.6139, lng: 77.209, name: "Delhi/Agra" },
        imageUrl: "https://images.unsplash.com/photo-1615551043360-33de8b5f410c?auto=format&fit=crop&q=80&w=800",
        tags: ["Mughal", "Jade", "Steel", "Imperial"]
    }
];

export async function seedRepository(currentUser: any) {
    if (!currentUser) return; // Allow any first user to seed if empty

    try {
        // 1. Seed Researchers
        console.log("Syncing researcher nodes with global network...");
        for (const dummy of DUMMY_RESEARCHERS) {
            const userRef = doc(db, 'users', dummy.id);
            const userDoc = await getDoc(userRef);
            if (!userDoc.exists()) {
                await setDoc(userRef, {
                    id: dummy.id,
                    email: dummy.email,
                    name: dummy.name,
                    role: 'researcher',
                    joinedAt: Date.now(),
                    createdAt: serverTimestamp(),
                    specialization: dummy.specialization,
                    xp: 2500,
                    level: 5,
                    badges: [{ id: 'founding', name: 'Founding Researcher', earnedAt: Date.now(), icon: 'Shield' }]
                });
            }
        }

        // 2. Seed Artifacts
        const q = query(collection(db, 'artifacts'), limit(1));
        const snapshot = await getDocs(q);
        
        if (snapshot.empty) {
            console.log("Seeding global archaeological archive to Firebase...");
            for (const item of manualDataset) {
                await addDoc(collection(db, 'artifacts'), {
                    ...item,
                    isVerified: true,
                    timestamp: Date.now(),
                    createdAt: serverTimestamp(),
                    userId: currentUser.id,
                    userName: currentUser.name,
                    tags: item.tags || []
                });
            }
            console.log("Seeding complete.");
        }
    } catch (e: any) {
        console.warn("Firestore seeding failed (potentially due to quota restrictions), activating local fallback seeding: ", e.message || e);
        try {
            // Seeding researchers locally
            for (const dummy of DUMMY_RESEARCHERS) {
                await fetch('/api/mirror', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        type: 'USER',
                        data: {
                            id: dummy.id,
                            email: dummy.email,
                            name: dummy.name,
                            role: 'researcher',
                            joinedAt: Date.now(),
                            specialization: dummy.specialization,
                            xp: 2500,
                            level: 5,
                            badges: [{ id: 'founding', name: 'Founding Researcher', earnedAt: Date.now(), icon: 'Shield' }]
                        }
                    })
                });
            }

            // Seeding artifacts locally
            const resArtifacts = await fetch('/api/artifacts');
            if (resArtifacts.ok) {
                const existingArtifacts = await resArtifacts.json();
                if (existingArtifacts.length === 0) {
                    console.log("Local archive is empty. Seeding local library cache...");
                    for (const item of manualDataset) {
                        await fetch('/api/mirror', {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/json' },
                            body: JSON.stringify({
                                type: 'ARTIFACT',
                                data: {
                                    id: Math.random().toString(36).substring(7),
                                    ...item,
                                    isVerified: true,
                                    timestamp: Date.now(),
                                    userId: currentUser.id,
                                    userName: currentUser.name,
                                    tags: item.tags || []
                                }
                            })
                        });
                    }
                    console.log("Local library cache seeding complete.");
                }
            }
        } catch (innerErr) {
            console.error("Local database seeding fallback also failed: ", innerErr);
        }
    }
}
