import { Artifact } from '../types';

export const SEED_ARTIFACTS: Omit<Artifact, 'id' | 'userId' | 'userName' | 'timestamp'>[] = [
  {
    name: "Lion Capital of Ashoka",
    type: "Sculpture",
    rarityLevel: 5,
    description: "A polished sandstone capital featuring four Asiatic lions standing back to back, originally atop the Ashoka Pillar at Sarnath.",
    historicalContext: "Commissioned by Emperor Ashoka to mark the site of Buddha's first sermon, it is now the national emblem of India.",
    estimatedEra: "250 BC",
    civilization: "Mauryan Empire",
    location: {
      lat: 25.3761,
      lng: 83.0227,
      name: "Sarnath, Varanasi"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Uttar Pradesh"
    },
    imageUrl: "https://images.unsplash.com/photo-1589182397057-074f67b9405e?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Buddhist Art", "Imperial", "Sandstone", "Emblematic"],
    confidenceScore: 1.0,
    isVerified: true,
    materialAnalysis: "Chunar sandstone with a characteristic 'Mauryan polish' that remains lustrous after 2,200 years.",
    culturalSignificance: "Fundamental symbol of Indian statehood and Buddhist philosophy.",
    historicalUsage: "Commemorative Pillar Capital",
    socialStructureInference: "Sophisticated central authority with wide-reaching religious patronage.",
    stratigraphy: {
      depth: 1.2,
      layer: "Ashland Fill",
      description: "Excavated near the Main Shrine at Sarnath."
    }
  },
  {
    name: "Pashupati Seal",
    type: "Seal",
    rarityLevel: 5,
    description: "A steatite seal depicting a seated, horned figure surrounded by animals, interpreted as a proto-Shiva deity.",
    historicalContext: "One of the most complex seals found in the Indus Valley, providing deep insight into early Harappan religious beliefs.",
    estimatedEra: "2350–2000 BC",
    civilization: "Indus Valley Civilization",
    location: {
      lat: 27.3292,
      lng: 68.1367,
      name: "Mohenjo-daro (Accession: National Museum, Delhi)"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Delhi"
    },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Harappan", "Steatite", "Glyptic", "Proto-Shiva"],
    confidenceScore: 0.99,
    isVerified: true,
    materialAnalysis: "Glazed steatite with high-temperature firing signature.",
    culturalSignificance: "Primary evidence of continuity in South Asian religious iconography.",
    historicalUsage: "Commercial and Ritual Identification",
    socialStructureInference: "Evidence of a merchant-priest class and organized urban religion.",
    stratigraphy: {
      depth: 3.5,
      layer: "Mature Harappan Phase",
      description: "Recovered from the lower town residential area."
    }
  },
  {
    name: "Iron Pillar of Delhi",
    type: "Monolith",
    rarityLevel: 5,
    description: "A 7.21-meter tall iron pillar famous for its high resistance to corrosion, showcasing advanced metallurgy.",
    historicalContext: "Originally erected by Chandragupta II, it possesses an inscription in Sanskrit in the Brahmi script.",
    estimatedEra: "4th - 5th Century AD",
    civilization: "Gupta Empire",
    location: {
      lat: 28.5247,
      lng: 77.1855,
      name: "Qutb Complex, Delhi"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Delhi"
    },
    imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Metallurgy", "Iron", "Inscription", "Gupta"],
    confidenceScore: 1.0,
    isVerified: true,
    materialAnalysis: "Wrought iron with high phosphorus content; protective 'misawite' layer prevents rust.",
    culturalSignificance: "Global benchmark for ancient metallurgical engineering.",
    historicalUsage: "Victory Pillar (Dhvaja)",
    socialStructureInference: "Highly advanced technological guilds operating under imperial patronage.",
    stratigraphy: {
      depth: 0.0,
      layer: "Exposed Surface",
      description: "Resting on a grid of iron bars soldered into the stone pavement."
    }
  },
  {
    name: "Nataraja Bronze (Chola Masterpiece)",
    type: "Sculpture",
    rarityLevel: 5,
    description: "A bronze sculpture depicting the Hindu god Shiva as the cosmic dancer (Nataraja).",
    historicalContext: "Produced during the Chola dynasty, it reached its sensory and technical peak between the 9th and 13th centuries.",
    estimatedEra: "11th Century AD",
    civilization: "Chola Dynasty",
    location: {
      lat: 11.4102,
      lng: 79.6935,
      name: "Chidambaram (National Museum, Delhi)"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Tamil Nadu"
    },
    imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Chola Bronze", "Shiva", "Tandava", "Iconography"],
    confidenceScore: 0.98,
    isVerified: true,
    materialAnalysis: "Panchaloha (five-metal alloy: gold, silver, copper, tin, lead).",
    culturalSignificance: "Highest - Universal symbol of Hindu art and philosophy.",
    historicalUsage: "Processional Deity",
    socialStructureInference: "Sophisticated temple-based economy and religious statecraft.",
    stratigraphy: {
      depth: 0.0,
      layer: "Archival",
      description: "Preserved in museum collections."
    }
  },
  {
    name: "Dancing Girl of Mohenjo-daro",
    type: "Statue",
    rarityLevel: 5,
    description: "A small bronze statuette depicting a young woman with bangles and a confident pose.",
    historicalContext: "Evidence of the 'lost-wax' casting method used as early as 2500 BC in India.",
    estimatedEra: "2500 BC",
    civilization: "Indus Valley Civilization",
    location: {
      lat: 27.3292,
      lng: 68.1367,
      name: "Mohenjo-daro"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Delhi (Finding Site Mohenjo-daro)"
    },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Bronze Age", "Harappan", "Metalwork", "Miniature"],
    confidenceScore: 1.0,
    isVerified: true,
    materialAnalysis: "Bronze alloystatue.",
    culturalSignificance: "Crucial for understanding Harappan aesthetics and social roles.",
    historicalUsage: "Ornamental or Ritual",
    socialStructureInference: "Specialized artisans and established social hierarchies.",
    stratigraphy: {
      depth: 2.1,
      layer: "Intermediate III",
      description: "Excavated from a house in the industrial quarter."
    }
  },
  {
    name: "Didarganj Yakshi",
    type: "Sculpture",
    rarityLevel: 5,
    description: "A life-size sandstone statue of a yakshi (female guardian spirit) found in Bihar.",
    historicalContext: "One of the most famous examples of Mauryan court art, known for its incredible polish and realism.",
    estimatedEra: "3rd Century BC",
    civilization: "Mauryan Empire",
    location: {
      lat: 25.5941,
      lng: 85.1376,
      name: "Patna Museum"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Bihar"
    },
    imageUrl: "https://images.unsplash.com/photo-1620002131972-23c8e44923f1?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Mauryan Art", "Yakshi", "Sandstone", "Patna"],
    confidenceScore: 0.99,
    isVerified: true,
    materialAnalysis: "Polished Chunar sandstone.",
    culturalSignificance: "Represents the feminine ideal and early courtly art in India.",
    historicalUsage: "Temple or Royal Guard",
    socialStructureInference: "Evidence of royal patronage and complex artisanal guilds.",
    stratigraphy: {
      depth: 1.0,
      layer: "Alluvial Silt",
      description: "Found on the banks of the Ganges."
    }
  },
  {
    name: "Lothal Dockyard",
    type: "Infrastructure",
    rarityLevel: 5,
    description: "The world's earliest known dockyard, an engineering marvel of the Bronze Age.",
    historicalContext: "Connected the Indus city of Lothal to the Gulf of Khambhat for maritime trade with Mesopotamia.",
    estimatedEra: "2400 BC",
    civilization: "Indus Valley Civilization",
    location: {
      lat: 22.5200,
      lng: 72.2500,
      name: "Lothal, Gujarat"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Gujarat"
    },
    imageUrl: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Maritime", "Dock", "Indus Valley", "Engineering"],
    confidenceScore: 0.99,
    isVerified: true,
    materialAnalysis: "Burnt brick masonry with hydraulic plaster.",
    culturalSignificance: "Proof of Harappan dominance in ancient sea trade.",
    historicalUsage: "Trade and Shipbuilding",
    socialStructureInference: "Highly organized port authority and maritime administrative structure.",
    stratigraphy: {
      depth: 3.0,
      layer: "Estuarine Silt",
      description: "Massive rectangular basin excavated in the low-lying part of the city."
    }
  },
  {
    name: "Rani ki Vav Stepwell",
    type: "Architecture",
    rarityLevel: 5,
    description: "A multi-storeyed stepwell with over 800 sculptures, designed as an inverted temple.",
    historicalContext: "Built by Queen Udayamati in memory of her husband Bhimdev I of the Solanki dynasty.",
    estimatedEra: "1063 AD",
    civilization: "Solanki Dynasty",
    location: {
      lat: 23.8580,
      lng: 72.1020,
      name: "Patan, Gujarat"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Gujarat"
    },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Architecture", "Water Management", "Solanki", "UNESCO"],
    confidenceScore: 1.0,
    isVerified: true,
    materialAnalysis: "Ornately carved sandstone.",
    culturalSignificance: "Peak of Maru-Gurjara architectural style and water sanctification.",
    historicalUsage: "Water Access and Religious Space",
    socialStructureInference: "State-led community resource projects with high artistic value.",
    stratigraphy: {
      depth: 27.0,
      layer: "Aquifer Level",
      description: "Subterranean structure reaching the water table."
    }
  },
  {
    name: "Shore Temple",
    type: "Architecture",
    rarityLevel: 5,
    description: "One of the oldest structural stone temples of South India, built by the Pallavas.",
    historicalContext: "Part of the Group of Monuments at Mahabalipuram, it face the Bay of Bengal.",
    estimatedEra: "700 – 728 AD",
    civilization: "Pallava Dynasty",
    location: {
      lat: 12.6167,
      lng: 80.1917,
      name: "Mahabalipuram"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Tamil Nadu"
    },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Dravidian Architecture", "Pallava", "Coastline", "Stone Temple"],
    confidenceScore: 0.98,
    isVerified: true,
    materialAnalysis: "Granite blocks cut from the local rock.",
    culturalSignificance: "Foundation of Dravidian temple architecture.",
    historicalUsage: "Religious Worship and Lighthouse Functionalism",
    socialStructureInference: "A maritime-oriented kingdom with significant religious investment.",
    stratigraphy: {
      depth: 0.0,
      layer: "Surface",
      description: "Exposed granite foundation on the coast."
    }
  },
  {
    name: "Sanchi Stupa East Gate",
    type: "Architecture",
    rarityLevel: 5,
    description: "A highly ornate gateway (torana) of the Great Stupa of Sanchi.",
    historicalContext: "Commissioned by the Satavahanas to enclose the original Mauryan brick structure.",
    estimatedEra: "1st Century BC",
    civilization: "Satavahana Empire",
    location: {
      lat: 23.4792,
      lng: 77.7397,
      name: "Sanchi"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Madhya Pradesh"
    },
    imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Buddhist Narrative", "Torana", "Satavahana", "Relief"],
    confidenceScore: 0.99,
    isVerified: true,
    materialAnalysis: "Fine-grained red sandstone.",
    culturalSignificance: "Primary source for early Buddhist aniconic art and social history.",
    historicalUsage: "Ceremonial Threshold",
    socialStructureInference: "Evidence of diverse donors (guilds, laymen, monks).",
    stratigraphy: {
      depth: 0.0,
      layer: "Superstructure",
      description: "Part of the enclosure wall of the Great Stupa."
    }
  },
  {
    name: "Vikramshila University Seal",
    type: "Seal",
    rarityLevel: 4,
    description: "A clay seal belonging to the Vikramshila Mahavihara, a Buddhist university.",
    historicalContext: "Founded by King Dharmapala, it was a major center of Vajrayana Buddhism.",
    estimatedEra: "8th Century AD",
    civilization: "Pala Empire",
    location: {
      lat: 25.3283,
      lng: 87.2023,
      name: "Antichak, Bihar"
    },
    region: {
      continent: "Asia",
      country: "India",
      state: "Bihar"
    },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    extraImages: [],
    tags: ["Pala", "Buddhist University", "Clay Seal", "Academic"],
    confidenceScore: 0.97,
    isVerified: true,
    materialAnalysis: "Fired terracotta clay.",
    culturalSignificance: "Vital record of medieval Indian higher education systems.",
    historicalUsage: "Administrative and Official Documentation",
    socialStructureInference: "State-funded monastic education system with international students.",
    stratigraphy: {
      depth: 1.5,
      layer: "Monastic Level II",
      description: "Found in one of the central cells of the monastery."
    }
  },
  {
    name: "Diamond-encrusted Mughal Dagger",
    type: "Weaponry",
    rarityLevel: 5,
    civilization: "Mughal Empire",
    description: "A ceremonial dagger (khanjar) with a hilt made of jade and inlaid with diamonds and rubies.",
    culturalSignificance: "Demonstrates the opulence and artisanal brilliance of the Mughal court.",
    historicalContext: "The Mughals were renowned for their exquisite jewelry and weaponry, blending Persian and Indian styles.",
    estimatedEra: "17th Century AD",
    materialAnalysis: "Jade, Steel, Diamonds, Rubies",
    historicalUsage: "Royal Ceremony and Status Symbol",
    socialStructureInference: "Highly stratified society with extreme wealth concentrated in the imperial family.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Delhi" },
    location: { lat: 28.6139, lng: 77.2090, name: "Red Fort" },
    imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
    tags: ["Mughal", "Jade", "Jeweled"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Archival", description: "Acquisition from Private Collection" }
  },
  {
    name: "Golconda Diamond",
    type: "Gemstone",
    rarityLevel: 5,
    civilization: "Kakatiya / Mughal",
    description: "A large, high-clarity diamond typical of those sourced from the Golconda mines.",
    culturalSignificance: "Symbol of divine right and imperial power.",
    historicalContext: "Golconda was the diamond capital of the ancient world, producing stones like the Hope and Koh-i-Noor.",
    estimatedEra: "13th - 16th Century AD",
    materialAnalysis: "Diamond (Carbon)",
    historicalUsage: "Crown Jewel",
    socialStructureInference: "Control over high-value natural resources as a basis for political power.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Telangana" },
    location: { lat: 17.3833, lng: 78.4011, name: "Golconda Fort" },
    imageUrl: "https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?auto=format&fit=crop&q=80&w=800",
    tags: ["Gemstone", "Golconda", "Imperial"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Archival", description: "Sourced from the mines" }
  },
  {
    name: "Nalanda Mahavihara Seal",
    type: "Seal",
    rarityLevel: 5,
    civilization: "Gupta / Pala Empire",
    description: "The official seal of the Nalanda University, featuring the dharma-chakra and two deer.",
    culturalSignificance: "Symbolizes the global importance of Nalanda as a center of knowledge.",
    historicalContext: "Nalanda was one of the first residential universities in the world, attracting scholars from across Asia.",
    estimatedEra: "5th - 12th Century AD",
    materialAnalysis: "Clay/Terracotta or Bronze",
    historicalUsage: "University Administration",
    socialStructureInference: "Establishment of world-class educational infrastructures supported by multiple dynasties.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Bihar" },
    location: { lat: 25.1320, lng: 85.1480, name: "Nalanda" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Nalanda", "Education", "Buddhist"],
    isVerified: true,
    stratigraphy: { depth: 1.2, layer: "Administrative Wing", description: "Found in situ at Nalanda site" }
  },
  {
    name: "Sultanganj Buddha",
    type: "Statue",
    rarityLevel: 5,
    civilization: "Gupta Empire",
    description: "A large copper-alloy statue of Buddha in the Abhaya Mudra, demonstrating advanced metal casting.",
    culturalSignificance: "Evidence of the high standard of Gupta metallurgy and spiritual art.",
    historicalContext: "Copper casting at this scale was a global rarity in the 1st millennium AD.",
    estimatedEra: "500–700 AD",
    materialAnalysis: "Copper Alloy (High purity)",
    historicalUsage: "Votive/Monastic Icon",
    socialStructureInference: "Monastic wealth and patronage from the Gupta court.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Bihar" },
    location: { lat: 25.2445, lng: 86.7328, name: "Sultanganj" },
    imageUrl: "https://images.unsplash.com/photo-1590050752117-23a9d7f66c3d?auto=format&fit=crop&q=80&w=800",
    tags: ["Gupta", "Bronze", "Buddhist"],
    isVerified: true,
    stratigraphy: { depth: 1.5, layer: "Alluvial", description: "Found during railway construction" }
  },
  {
    name: "Gupta Gold Dinara (Archer Type)",
    type: "Numismatics",
    rarityLevel: 5,
    civilization: "Gupta Empire",
    description: "A gold coin depicting King Chandragupta II as an archer with a bow and arrow.",
    culturalSignificance: "The 'Golden Age' marker of Indian history, reflecting economic might.",
    historicalContext: "The Guptas issued the most artistically refined gold coinage of ancient India.",
    estimatedEra: "375–415 AD",
    materialAnalysis: "High-purity Gold",
    historicalUsage: "International Trade and Imperial Prestige",
    socialStructureInference: "Highly monetized economy with stable central administration.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Delhi" },
    location: { lat: 28.6139, lng: 77.2090, name: "National Museum" },
    imageUrl: "https://images.unsplash.com/photo-1584144122606-fba4ec60a631?auto=format&fit=crop&q=80&w=800",
    tags: ["Gupta", "Gold Coin", "Archer"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Archival", description: "Bayana Hoard" }
  },
  {
    name: "Ashokan Rock Edict (Major XIV)",
    type: "Inscription",
    rarityLevel: 5,
    civilization: "Mauryan Empire",
    description: "A large granite boulder inscribed with 14 edicts promoting religious tolerance and non-violence.",
    culturalSignificance: "Earliest evidence of a state-sponsored ethics program in the world.",
    historicalContext: "Ashoka's edicts were placed along trade routes to reach the maximum population.",
    estimatedEra: "250 BC",
    materialAnalysis: "Igneous Rock (Granite)",
    historicalUsage: "Public Legal and Ethical Code",
    socialStructureInference: "Sophisticated bureaucracy and extensive road networks.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Gujarat" },
    location: { lat: 21.5167, lng: 70.4667, name: "Junagadh" },
    imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
    tags: ["Mauryan", "Brahmi", "Edict"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Exposed Surface", description: "Inscribed on natural rock face" }
  },
  {
    name: "Dokra Metal Figurine",
    type: "Metalwork",
    rarityLevel: 3,
    civilization: "Traditional Tribal (Dhokra)",
    description: "A hollow-cast brass figure of a horse and rider, featuring the distinctive 'thread-work' texture.",
    culturalSignificance: "A 4000-year continuous link to Harappan metal-casting technology.",
    historicalContext: "The lost-wax casting (cire perdue) technique is one of the oldest in the world.",
    estimatedEra: "Traditional (Centuries old)",
    materialAnalysis: "Brass/Bell Metal",
    historicalUsage: "Ritual Offering and Tribal Identity",
    socialStructureInference: "Resilient artisanal clusters maintaining ancient trade secrets for millennia.",
    confidenceScore: 0.95,
    region: { continent: "Asia", country: "India", state: "West Bengal" },
    location: { lat: 23.2333, lng: 87.0833, name: "Bankura" },
    imageUrl: "https://images.unsplash.com/photo-1620025375498-338c227fc64a?auto=format&fit=crop&q=80&w=800",
    tags: ["Tribal", "Metal Casting", "Dokra"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Living Heritage", description: "Contemporary artisanal production" }
  },
  {
    name: "Bidriware Ceremonial Plate",
    type: "Metalwork",
    rarityLevel: 4,
    civilization: "Bahmani Sultanate",
    description: "A black alloy plate with floral silver inlay (Teh-nishan technique).",
    culturalSignificance: "Represents the Indo-Persian aesthetic of the Deccan courts.",
    historicalContext: "The black color comes from a specific soil found only in the Bidar Fort area.",
    estimatedEra: "15th Century AD",
    materialAnalysis: "Zinc Alloy with Silver Inlay",
    historicalUsage: "Royal Tableware and Display",
    socialStructureInference: "Cosmopolitan elite culture in the Deccan Sultanates.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Karnataka" },
    location: { lat: 17.9124, lng: 77.5199, name: "Bidar" },
    imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
    tags: ["Bidriware", "Deccan", "Silver"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Archival", description: "Courtly Collection" }
  },
  {
    name: "Tanjore Painting",
    type: "Painting",
    rarityLevel: 4,
    civilization: "Maratha / Nayaka Era",
    description: "Classical South Indian painting characterized by rich, flat and vivid colors with gold foil overlay.",
    culturalSignificance: "Unique blend of fine art and relief work using semi-precious stones.",
    historicalContext: "Thanjavur paintings are known for their surface richness and compact composition.",
    estimatedEra: "18th Century AD",
    materialAnalysis: "Gold Foil and Semi-precious Stones on Wood",
    historicalUsage: "Sacred Iconography",
    socialStructureInference: "Persistence of royal devotional patronage during transitioning political powers.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Tamil Nadu" },
    location: { lat: 10.7870, lng: 79.1378, name: "Thanjavur" },
    imageUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&q=80&w=800",
    tags: ["Tanjore", "Gold", "Hindu Art"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Archival", description: "Temple collection" }
  },
  {
    name: "Jantar Mantar Sundial Segment",
    type: "Scientific Instrument",
    rarityLevel: 5,
    civilization: "Rajput States (Jaipur)",
    description: "A functional segment of the Samrat Yantra, the world's largest sundial.",
    culturalSignificance: "Apex of pre-modern Indian astronomical science.",
    historicalContext: "Sawai Jai Singh II built five such observatories across North India.",
    estimatedEra: "1734 AD",
    materialAnalysis: "Marble and Red Sandstone",
    historicalUsage: "Timekeeping and Celestial Tracking",
    socialStructureInference: "State-led focus on scientific rationalism in 18th century India.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Rajasthan" },
    location: { lat: 26.9248, lng: 75.8245, name: "Jaipur" },
    imageUrl: "https://images.unsplash.com/photo-1605333190861-f925ecf36bc4?auto=format&fit=crop&q=80&w=800",
    tags: ["Astronomy", "Rajasthan", "UNESCO"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Surface", description: "Part of the architectural complex" }
  },
  {
    name: "Maratha Bhavani Sword",
    type: "Weaponry",
    rarityLevel: 5,
    civilization: "Maratha Empire",
    description: "A long, straight-bladed sword (dhup) known for its flexible steel and high quality.",
    culturalSignificance: "Symbol of Chhatrapati Shivaji Maharaj's naval and military might.",
    historicalContext: "The original is said to have been presented by the goddess Bhavani.",
    estimatedEra: "17th Century AD",
    materialAnalysis: "High-grade Steel and Silver Inlay",
    historicalUsage: "Personal Weapon of the Emperor",
    socialStructureInference: "Highly professionalized military state with deep religious ethos.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Maharashtra" },
    location: { lat: 18.2435, lng: 73.6934, name: "Raigad Fort" },
    imageUrl: "https://images.unsplash.com/photo-1599508704512-2f19fe91f7a1?auto=format&fit=crop&q=80&w=800",
    tags: ["Maratha", "Sword", "Historical Heritage"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Archival", description: "Royal Armory" }
  },
  {
    name: "Rajput Rhino Hide Shield",
    type: "Armor",
    rarityLevel: 4,
    civilization: "Rajput States",
    description: "A durable, translucent shield made from cured rhinoceros hide, decorated with metal stars.",
    culturalSignificance: "Demonstrates the unique armor-making traditions of North India.",
    historicalContext: "Rhino hide was prized for being lightweight yet impenetrable to arrows.",
    estimatedEra: "16th - 17th Century AD",
    materialAnalysis: "Lacquered Rhino Hide and Brass",
    historicalUsage: "Battlefield Defense",
    socialStructureInference: "Culture of chivalry and individual martial prowess.",
    confidenceScore: 0.97,
    region: { continent: "Asia", country: "India", state: "Rajasthan" },
    location: { lat: 24.5854, lng: 73.7125, name: "Udaipur" },
    imageUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
    tags: ["Rajput", "Shield", "Mewar"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Archival", description: "City Palace Museum" }
  },
  {
    name: "Sun Temple Wheel of Konark",
    type: "Architecture",
    rarityLevel: 5,
    civilization: "Eastern Ganga Dynasty",
    description: "One of the 24 massive stone wheels of the Sun Temple, doubling as a precise sundial.",
    culturalSignificance: "Extreme engineering and astronomical precision of 13th-century Odisha.",
    historicalContext: "The temple was designed as a colossal processional chariot for the Sun God.",
    estimatedEra: "1250 AD",
    materialAnalysis: "Khondalite Stone",
    historicalUsage: "Religious Monument and Chronometry",
    socialStructureInference: "Highly organized maritime empire with advanced theological-scientific integration.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India", state: "Odisha" },
    location: { lat: 19.8876, lng: 86.0945, name: "Konark Sun Temple" },
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=80&w=800",
    tags: ["Konark", "Sun Temple", "Odisha", "Stone Carving"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Superstructure", description: "Temple exterior" }
  },
  {
    name: "Ajanta Cave 1 Fresco Fragment",
    type: "Painting",
    rarityLevel: 5,
    civilization: "Vakataka / Gupta Era",
    description: "A mural depiction of Padmapani Bodhisattva, known for its expressive eyes and graceful posture.",
    culturalSignificance: "High point of classical Indian painting and Buddhist spirituality.",
    historicalContext: "The Ajanta caves were carved into volcanic basalt over several centuries.",
    estimatedEra: "5th Century AD",
    materialAnalysis: "Natural Pigments on Lime Plaster",
    historicalUsage: "Sacred Space Decoration",
    socialStructureInference: "Monastic isolation supported by royal silk-road trade wealth.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Maharashtra" },
    location: { lat: 20.5519, lng: 75.7033, name: "Ajanta Caves" },
    imageUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&q=80&w=800",
    tags: ["Ajanta", "Buddhist Art", "Mural", "Classical"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Cave Interior", description: "North wall of Cave 1" }
  },
  {
    name: "Hoysaleswara Temple Nandi",
    type: "Sculpture",
    rarityLevel: 4,
    civilization: "Hoysala Empire",
    description: "A colossal, highly polished monolithic Nandi bull, covered in intricate jewelry carvings.",
    culturalSignificance: "Demonstrates the pinnacle of Hoysala micro-sculpting in soapstone.",
    historicalContext: "The Hoysala capital Halebid was a center of grand temple architectural experiments.",
    estimatedEra: "1121 AD",
    materialAnalysis: "Chloritic Schist (Soapstone)",
    historicalUsage: "Religious Votive (Vahana)",
    socialStructureInference: "Artisanal guilds (like the Ruvari family) enjoyed high social and economic status.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "Karnataka" },
    location: { lat: 13.2125, lng: 75.9926, name: "Halebidu" },
    imageUrl: "https://images.unsplash.com/photo-1620002131972-23c8e44923f1?auto=format&fit=crop&q=80&w=800",
    tags: ["Hoysala", "Soapstone", "Nandi", "Halebid"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Open Court", description: "Facing the main sanctum" }
  },
  {
    name: "Gandhara Standing Buddha Specimen",
    type: "Sculpture",
    rarityLevel: 5,
    civilization: "Kushana Empire (Gandhara School)",
    description: "A Greco-Buddhist style Buddha with heavy drapery and Hellenistic facial features.",
    culturalSignificance: "Evidence of the first anthropomorphic representations of the Buddha influenced by Silk Road trade.",
    historicalContext: "Found in the Peshawar valley, representing the syncretism of Greek and Indian art.",
    estimatedEra: "2nd Century AD",
    materialAnalysis: "Gray Schist",
    historicalUsage: "Veneration in Stupa Complexes",
    socialStructureInference: "Highly cosmopolitan society with active Mediterranean trade links.",
    confidenceScore: 0.99,
    region: { continent: "Asia", country: "India/Pakistan", state: "Gandhara" },
    location: { lat: 34.015, lng: 71.5249, name: "Taxila/Peshawar" },
    imageUrl: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&q=80&w=800",
    tags: ["Gandhara", "Kushana", "Buddhist", "Schist"],
    isVerified: true,
    stratigraphy: { depth: 2.5, layer: "Monastic Level", description: "Votive Stupa Base" }
  },
  {
    name: "Indus Valley Pashupati Seal",
    type: "Inscription",
    rarityLevel: 5,
    civilization: "Indus Valley Civilization (Harappan)",
    description: "Steatite seal depicting a seated figure surrounded by animals, potentially an early form of Shiva.",
    culturalSignificance: "Foundational evidence of Proto-Shiva worship and advanced glyptic art.",
    historicalContext: "Recovered from the lower town of Mohenjo-Daro.",
    estimatedEra: "2500 BCE",
    materialAnalysis: "Glazed Steatite (Soapstone)",
    historicalUsage: "Authentication for Trade Goods",
    socialStructureInference: "Highly organized urban bureaucracy with developed standard weights and measures.",
    confidenceScore: 1.0,
    region: { continent: "Asia", country: "India", state: "Sindh/Gujarat" },
    location: { lat: 27.3292, lng: 68.1384, name: "Mohenjo-Daro" },
    imageUrl: "https://images.unsplash.com/photo-1608659597669-b45511723fbd?auto=format&fit=crop&q=80&w=800",
    tags: ["Indus Valley", "Harappa", "Seal", "Bronze Age"],
    isVerified: true,
    stratigraphy: { depth: 4.0, layer: "Intermediate III", description: "Residential Sector B" }
  },
  {
    name: "Mughal Imperial Dagger (Khanjar)",
    type: "Weaponry",
    rarityLevel: 4,
    civilization: "Mughal Empire",
    description: "Damascus steel blade with a nephrite jade hilt carved into a ram's head.",
    culturalSignificance: "Represents the pinnacle of Mughal metalwork and lapidary arts.",
    historicalContext: "Likely belonging to the reign of Shah Jahan, used as a ceremonial status symbol.",
    estimatedEra: "17th Century AD",
    materialAnalysis: "Damascus Steel, Jade, Gold Inlay",
    historicalUsage: "Royal Regalia",
    socialStructureInference: "Extreme wealth concentration in an imperial court with specialized luxury guilds.",
    confidenceScore: 0.98,
    region: { continent: "Asia", country: "India", state: "North India" },
    location: { lat: 28.6139, lng: 77.209, name: "Delhi/Agra" },
    imageUrl: "https://images.unsplash.com/photo-1615551043360-33de8b5f410c?auto=format&fit=crop&q=80&w=800",
    tags: ["Mughal", "Jade", "Steel", "Imperial"],
    isVerified: true,
    stratigraphy: { depth: 0, layer: "Palace Collection", description: "Royal Armory" }
  }
];

